import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { intel } from './useIntel';
import { activityLabel, narrativeLabel, locationLabel, actorLabels, relationshipLabels } from './actorPictureView';
export default function ActorIntelligence({actorId,accounts}){
  const [records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);intel('actorPicture',{actor_id:actorId}).then(r=>{if(active)setRecords(r.records||[])}).catch(e=>{if(active)setError(e.response?.data?.error||e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[actorId]);
  const channels=[...new Set(records.filter(r=>r.source_identity?.status!=='REGISTERED_ACCOUNT_CONFIRMED'&&!r.owned_channel?.account_id).map(r=>r.observed_publisher_handle||r.author).filter(Boolean))];
  return <section className="intel-card p-6 space-y-4"><div><h2 className="font-semibold text-lg">Actor Intelligence Picture</h2><p className="text-xs text-[#617789]">Public, jurisdiction-scoped evidence only · relationships do not prove ownership.</p></div>{loading?<p className="text-sm">Loading intelligence timeline...</p>:error?<p role="alert" className="text-sm text-red-700">{error}</p>:<><div><span className="intel-label">Registered / owned channels</span>{accounts.filter(a=>a.watchlist_id===actorId).map(a=><p key={a.id} className="text-sm">{a.handle||a.url} · REGISTERED ACCOUNT</p>)}{!accounts.some(a=>a.watchlist_id===actorId)&&<p className="text-sm">None recorded.</p>}</div><div><span className="intel-label">Related / observed publishers</span>{channels.map(h=><p key={h} className="text-sm">{h} · RELATED / OBSERVED ACCOUNT · ownership not confirmed</p>)}{!channels.length&&<p className="text-sm">None recorded.</p>}</div><div className="grid sm:grid-cols-2 gap-3 text-sm">{[['Activities',[...new Set(records.map(r=>activityLabel(r.intelligence_extraction)).filter(Boolean))]],['Locations',[...new Set(records.map(r=>locationLabel(r.intelligence_extraction,r)).filter(Boolean))]],['Narratives',[...new Set(records.map(r=>narrativeLabel(r.intelligence_extraction)).filter(Boolean))]],['Associated entities',[...new Set(records.flatMap(r=>[...(r.related_entities||[]),...actorLabels(r.intelligence_extraction)]).filter(Boolean))]],['Extracted relationships · not ownership',[...new Set(records.flatMap(r=>relationshipLabels(r.intelligence_extraction)))]],['Supervision signals',[...new Set(records.map(r=>r.supervision_screening?.supervision_signal).filter(Boolean))]]].map(([label,values])=><div key={label}><span className="intel-label">{label}</span><p>{values.join(' · ')||'Not yet recorded / approved'}</p></div>)}</div><div><span className="intel-label">Timeline · {records.length} related records · {records.filter(r=>r.entity_relationships?.some(e=>e.relationship_type==='FEATURES')).length} featured appearances in submitted public evidence</span>{records.map(r=><Link to={`/intelligence/${r.id}`} key={r.id} className="block border-t py-3 text-sm space-y-1"><p className="font-semibold text-[#126d91]">{r.intelligence_id} · {r.title}</p><p>{r.publication_date||r.publication_datetime||r.collection_datetime?.slice(0,10)||'Date unknown'} · {r.entity_relationships?.map(x=>x.relationship_type).join(', ')||'Registered source / human link'} · {r.priority||'—'} · {r.review_status||'—'}</p><p>Activity: {activityLabel(r.intelligence_extraction)||'Not human-approved'} · Location: {locationLabel(r.intelligence_extraction,r)||'Not recorded'}</p><p>Narrative: {narrativeLabel(r.intelligence_extraction)||'Not human-approved'} · Signal: {r.supervision_screening?.supervision_signal||'Not determined'}</p></Link>)}{!records.length&&<p className="text-sm">No related public intelligence in your jurisdiction.</p>}</div></>}</section>;
}