import { Link } from 'react-router-dom';
import Status from './Status';
import { useLanguage } from '@/lib/LanguageContext';
const fmt=v=>{if(!v)return '';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('en-GB',{year:'numeric',month:'short',day:'2-digit',hour:String(v).includes('T')?'2-digit':undefined,minute:String(v).includes('T')?'2-digit':undefined})};
export default function AssistantRecords({records}){
  const {t}=useLanguage();
  if(!records?.length)return null;
  return <div className="mt-5 border-t border-[#e4e9ef] pt-4 space-y-3"><p className="text-xs font-bold uppercase tracking-wider text-[#53657b]">{t('supporting_intelligence_records')}</p>{records.map(r=><div key={r.id} className="rounded-lg border border-[#e4e9ef] bg-white p-3 text-sm"><Link to={'/intelligence/'+r.id} className="font-semibold text-[#126d91] hover:underline">{r.intelligence_id} · {r.title}</Link><div className="mt-1 text-xs text-[#617789] space-y-0.5">{r.publication_date&&<p>{t('published_label')}: {fmt(r.publication_date)}</p>}{r.collection_datetime&&<p>{t('collected_label')}: {fmt(r.collection_datetime)}</p>}{r.validated_at&&<p>{t('validated_label2')}: {fmt(r.validated_at)}</p>}<p>{t('confirmed_jurisdiction_label')}: {r.jurisdiction}</p></div>{r.source_name&&<p className="text-xs text-[#617789] mt-1">{t('source_publisher')}: {r.source_name}</p>}{r.approved_count>0&&<p className="text-xs text-[#53657b] mt-1">{r.approved_count} {r.approved_count===1?t('human_approved_field_singular'):t('human_approved_field_plural')}</p>}{r.candidate&&<p className="text-xs text-[#53657b] mt-1">{t('registered_owned_channel_lower')} · {r.candidate} · {r.owned_platform}</p>}<div className="flex flex-wrap gap-1.5 mt-2"><Status value={r.priority}/><Status value={r.review_status}/><Status value={r.evidence_type}/><Status value={r.verification_status}/></div></div>)}</div>;
}
