import { useState } from 'react';
import { registry } from '@/components/intel/useIntel';
import { err, Notice } from '@/components/intel/Fields';
import { useLanguage } from '@/lib/LanguageContext';
export default function CategoryManager({categories,refresh,authorized}){
 const {t}=useLanguage();
 const [name,setName]=useState(''),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{if(editing){await registry('updateCategory',{name:editing.name,active:editing.active},editing.id);setEditing(null)}else{await registry('category',{name});setName('')}await refresh()}catch(e){setError(err(e))}finally{setBusy(false)}}
 async function toggle(c){setBusy(true);setError('');try{await registry('updateCategory',{name:c.name,active:!c.active},c.id);await refresh()}catch(e){setError(err(e))}finally{setBusy(false)}}
 return <section className="intel-card p-6 space-y-4"><h2 className="font-semibold">{t('potential_issue_categories')}</h2><p className="text-xs text-[#8293a4]">{t('category_history_note')}</p><Notice error={error}/><div className="space-y-2">{categories.map(c=><div key={c.id} className="flex flex-wrap items-center justify-between gap-2 border-b border-[#edf1f5] py-2 text-sm"><span>{c.name} <span className="text-xs text-[#8293a4]">{c.active?t('active'):t('inactive')}</span></span>{authorized&&<div className="flex gap-3"><button disabled={busy} type="button" onClick={()=>setEditing({...c})} className="text-[#146a8b]">{t('edit')}</button><button disabled={busy} type="button" onClick={()=>toggle(c)} className="text-[#146a8b]">{c.active?t('deactivate'):t('activate')}</button></div>}</div>)}</div>{authorized&&(editing?<form onSubmit={submit} className="space-y-2"><input className="intel-input" aria-label={t('edit_category_name')} value={editing.name} required onChange={e=>setEditing({...editing,name:e.target.value})}/><button className="intel-button" disabled={busy}>{t('save_category')}</button> <button type="button" className="intel-ghost" onClick={()=>setEditing(null)}>{t('cancel')}</button></form>:<form onSubmit={submit} className="flex flex-wrap gap-2"><input className="intel-input max-w-sm" placeholder={t('new_category')} value={name} required onChange={e=>setName(e.target.value)}/><button className="intel-button" disabled={busy}>{t('add_category')}</button></form>)}</section>
}