import { useState } from 'react';
import JurisdictionFields from './JurisdictionFields';
import { Notice, err } from './Fields';
import SourceGeography from './SourceGeography';
export default function JurisdictionConfirmation({item,onSaved,canConfirm,onRecordAction}){
 const suggestion=item.ai_geography;
 const [draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const proposed=item.proposed_geography;
 const initial=()=>confirmed?{jurisdiction_type:item.jurisdiction_type,province_code:item.province_code||'',regency_city_code:item.regency_city_code||'',geographic_assignments:item.geographic_assignments||[]}:suggestion?.jurisdiction_type&&suggestion.jurisdiction_type!=='Unresolved'?{jurisdiction_type:suggestion.jurisdiction_type,province_code:suggestion.province_code||'',regency_city_code:suggestion.regency_city_code||'',geographic_assignments:suggestion.geographic_assignments||[]}:{jurisdiction_type:proposed?.jurisdiction_type||item.jurisdiction_type||'Unresolved',province_code:proposed?.province_code||item.province_code||'',regency_city_code:proposed?.regency_city_code||item.regency_city_code||'',geographic_assignments:proposed?.geographic_assignments||item.geographic_assignments||[]};
 const confirmed=item.jurisdiction_confirmed===true;
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await onRecordAction('confirmJurisdiction',{...draft},item.id);setDraft(null);await onSaved()}catch(e){setError(err(e))}finally{setBusy(false)}}
 return <section className="intel-card p-6 space-y-3"><h2 className="font-semibold text-lg">Jurisdiction</h2><p className="text-sm">{confirmed?<>{item.jurisdiction_type} · {item.geographic_assignments?.map(x=>[x.regency_city,x.province].filter(Boolean).join(', ')).join(' · ')||'National'} · Confirmed by {item.jurisdiction_confirmed_by||'authorized user'}</>:<strong>Requires jurisdiction resolution · Not visible to regional users</strong>}</p>{!confirmed&&proposed?.jurisdiction_type&&proposed.jurisdiction_type!=='Unresolved'&&<p className="text-sm">Submitter-proposed jurisdiction: {proposed.jurisdiction_type} · {[proposed.regency_city,proposed.province].filter(Boolean).join(', ')||proposed.geographic_assignments?.map(x=>[x.regency_city,x.province].filter(Boolean).join(', ')).join(' · ')}</p>}{suggestion&&<SourceGeography geography={suggestion}/>}<Notice error={error}/>{canConfirm&&item.geographic_mismatch?.status!=='pending'&&(draft?<form onSubmit={save} className="space-y-4"><JurisdictionFields value={draft} onChange={setDraft}/><button disabled={busy} className="intel-button">{busy?'Saving...':'Confirm Jurisdiction'}</button> <button type="button" className="intel-ghost" onClick={()=>setDraft(null)}>Cancel</button></form>:<button className="intel-ghost" onClick={()=>setDraft(initial())}>{confirmed?'Change confirmed jurisdiction':'Confirm Jurisdiction'}</button>)}</section>;
}