import { useState } from 'react';
import { suggestionNames as names } from './triageSections';
import { useLanguage } from '@/lib/LanguageContext';
const noIssue='NO APPARENT ELECTION-SUPERVISION ISSUE';
export default function PendingSuggestionRow({name,value,decision,confidence,onDecide,busy}){
 const {t}=useLanguage();
 const [editing,setEditing]=useState(false),[changing,setChanging]=useState(false),[rejecting,setRejecting]=useState(false),[reason,setReason]=useState(''),[draft,setDraft]=useState('');
 const noIssueFound=name==='issue_category'&&(value===noIssue||value==='NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED');
 const showValue=noIssueFound?'NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED':value;
 const save=async(status,text,reason)=>{if(await onDecide(name,status,text,reason)){setEditing(false);setChanging(false);setRejecting(false);setReason('')}};
 return <div className="rounded-lg border border-[#e3eaf0] p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><h4 className="text-xs font-bold uppercase tracking-wide text-[#53657b]">{names[name]}</h4><span className="text-xs text-[#607b8a]">{decision?.status||t('awaiting_human_review_label')}</span></div><p className="text-sm whitespace-pre-wrap break-words max-h-48 overflow-auto">{showValue}</p>{noIssueFound&&<p className="text-xs leading-5 text-[#617789]">{t('no_issue_triage_note')}</p>}{confidence&&<p className="text-xs text-[#667b8e]">{t('ai_confidence')}: {confidence}</p>}{decision?.status&&<p className="text-xs text-[#42657a] max-h-48 overflow-auto whitespace-pre-wrap break-words">{t('human_decision_label')}: {decision.status.replace('Human ','')}{decision.status!=='Human Rejected'&&decision.value&&` · Final: ${decision.value===noIssue?'NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED':decision.value}`}{decision.status==='Human Rejected'&&decision.reason&&` · Reason: ${decision.reason}`}</p>}{decision?.status&&!changing?<button type="button" disabled={busy} className="text-xs font-semibold text-[#126d91] hover:underline" onClick={()=>setChanging(true)}>{t('change_decision')}</button>:<div className="flex flex-wrap gap-2"><button type="button" disabled={busy} className="intel-ghost" onClick={()=>save('Human Accepted')}>{t('accept')}</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>{setDraft(decision?.value||value);setEditing(true)}}>{t('modify')}</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>{setEditing(false);setRejecting(true)}}>{t('reject')}</button>{changing&&<button type="button" className="intel-ghost" onClick={()=>{setChanging(false);setEditing(false)}}>{t('cancel_change')}</button>}</div>}{rejecting&&<div className="space-y-2"><label className="intel-label" htmlFor={`reject-${name}`}>{t('reason_rejection')}</label><textarea id={`reject-${name}`} className="intel-input" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} rows={2}/><button type="button" disabled={busy||reason.trim().length<5} className="intel-button" onClick={()=>{save('Human Rejected','',reason)}}>{t('save_rejection')}</button> <button type="button" className="intel-ghost" onClick={()=>setRejecting(false)}>{t('cancel')}</button></div>}{editing&&<div className="space-y-2"><textarea className="intel-input" aria-label={`Modified ${names[name]}`} value={draft} onChange={e=>setDraft(e.target.value)} rows={name==='english_translation'?5:2}/><button type="button" disabled={busy||!draft.trim()} className="intel-button" onClick={()=>{save('Human Modified',draft)}}>{t('save_modified_value')}</button> <button type="button" className="intel-ghost" onClick={()=>setEditing(false)}>Cancel</button></div>}</div>;
}