import { useState } from 'react';
import { suggestionNames as names } from './triageSections';
const noIssue='NO APPARENT ELECTION-SUPERVISION ISSUE';
export default function PendingSuggestionRow({name,value,decision,confidence,onDecide,busy}){
 const [editing,setEditing]=useState(false),[changing,setChanging]=useState(false),[rejecting,setRejecting]=useState(false),[reason,setReason]=useState(''),[draft,setDraft]=useState('');
 const noIssueFound=name==='issue_category'&&(value===noIssue||value==='NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED');
 const showValue=noIssueFound?'NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED':value;
 const save=async(status,text,reason)=>{if(await onDecide(name,status,text,reason)){setEditing(false);setChanging(false);setRejecting(false);setReason('')}};
 return <div className="rounded-lg border border-[#e3eaf0] p-4 space-y-3"><div className="flex flex-wrap justify-between gap-2"><h4 className="text-xs font-bold uppercase tracking-wide text-[#53657b]">{names[name]}</h4><span className="text-xs text-[#607b8a]">{decision?.status||'Awaiting human review'}</span></div><p className="text-sm whitespace-pre-wrap break-words max-h-48 overflow-auto">{showValue}</p>{noIssueFound&&<p className="text-xs leading-5 text-[#617789]">Based on the currently available source material, the AI did not identify an apparent election-supervision issue. This is a triage assessment, not a legal determination, and may be changed by an authorized analyst.</p>}{confidence&&<p className="text-xs text-[#667b8e]">AI confidence: {confidence}</p>}{decision?.status&&<p className="text-xs text-[#42657a] max-h-48 overflow-auto whitespace-pre-wrap break-words">Human decision: {decision.status.replace('Human ','')}{decision.status!=='Human Rejected'&&decision.value&&` · Final: ${decision.value===noIssue?'NO APPARENT ELECTION-SUPERVISION ISSUE IDENTIFIED':decision.value}`}{decision.status==='Human Rejected'&&decision.reason&&` · Reason: ${decision.reason}`}</p>}{decision?.status&&!changing?<button type="button" disabled={busy} className="text-xs font-semibold text-[#126d91] hover:underline" onClick={()=>setChanging(true)}>Change decision</button>:<div className="flex flex-wrap gap-2"><button type="button" disabled={busy} className="intel-ghost" onClick={()=>save('Human Accepted')}>ACCEPT</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>{setDraft(decision?.value||value);setEditing(true)}}>MODIFY</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>{setEditing(false);setRejecting(true)}}>REJECT</button>{changing&&<button type="button" className="intel-ghost" onClick={()=>{setChanging(false);setEditing(false)}}>Cancel change</button>}</div>}{rejecting&&<div className="space-y-2"><label className="intel-label" htmlFor={`reject-${name}`}>Reason for rejection (required)</label><textarea id={`reject-${name}`} className="intel-input" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} rows={2}/><button type="button" disabled={busy||reason.trim().length<5} className="intel-button" onClick={()=>{save('Human Rejected','',reason)}}>Save rejection</button> <button type="button" className="intel-ghost" onClick={()=>setRejecting(false)}>Cancel</button></div>}{editing&&<div className="space-y-2"><textarea className="intel-input" aria-label={`Modified ${names[name]}`} value={draft} onChange={e=>setDraft(e.target.value)} rows={name==='english_translation'?5:2}/><button type="button" disabled={busy||!draft.trim()} className="intel-button" onClick={()=>{save('Human Modified',draft)}}>Save modified value</button> <button type="button" className="intel-ghost" onClick={()=>setEditing(false)}>Cancel</button></div>}</div>;
}