import { useEffect, useState } from 'react';
import { intel } from './useIntel';
import { Field, Notice, err } from './Fields';

export default function SourceCorrection({item,onSaved,onRecordAction,canTriage}){
 const [source,setSource]=useState(item),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useEffect(()=>setSource(item),[item.updated_date]);
 async function retrieve(){setBusy(true);setError('');try{const r=await intel('retrieve',{url:item.source_url});if(!r.available)setStatus('SOURCE RETRIEVAL UNAVAILABLE');else{if(!item.original_content||!item.author||!item.publication_datetime||!item.original_language||item.original_language==='Undetermined')await onRecordAction('recoverSource',{automatic:true},item.id);setSource(x=>({...x,...Object.fromEntries(Object.entries(r).filter(([k,v])=>v&&(!x[k]||k==='original_language'&&x[k]==='Undetermined')))}));setStatus('Source fields recovered where available.');await onSaved();}}catch(e){setStatus('SOURCE RETRIEVAL UNAVAILABLE');setError(err(e))}finally{setBusy(false)}}
 async function save(e){e.preventDefault();setBusy(true);setError('');try{await onRecordAction('recoverSource',source,item.id);setStatus('Manual source fields saved.');await onSaved()}catch(e){setError(err(e))}finally{setBusy(false)}}
 
 return <div className="space-y-4"><section className="intel-card p-5 space-y-4"><h3 className="font-semibold">URL source recovery · {item.intelligence_id}</h3><p className="text-sm break-all">{item.source_url}</p><Notice error={error}/><button type="button" className="intel-ghost" disabled={busy} onClick={retrieve}>{busy?'Retrieving...':'Retrieve source'}</button>{status&&<p role="status" className="text-sm font-semibold text-[#a04724]">{status}</p>}<p className="text-xs">If retrieval is unavailable, paste source material below. Existing original fields are never replaced.</p><form onSubmit={save} className="space-y-3"><Field label="Original headline" value={source.title} onChange={v=>setSource(x=>({...x,title:v}))}/><Field label="Original content / extract" as="textarea" value={source.original_content} onChange={v=>setSource(x=>({...x,original_content:v}))}/><div className="grid md:grid-cols-3 gap-3"><Field label="Author / account" value={source.author} onChange={v=>setSource(x=>({...x,author:v}))}/><Field label="Publication date" type="datetime-local" value={source.publication_datetime?.slice(0,16)} onChange={v=>setSource(x=>({...x,publication_datetime:v}))}/><Field label="Original language" value={source.original_language==='Undetermined'?'':source.original_language} onChange={v=>setSource(x=>({...x,original_language:v}))}/></div><button disabled={busy} className="intel-button">Save missing source fields</button></form></section>{canTriage&&source.original_content?.trim().length>=80&&<a href="#ai-triage-review" className="text-sm font-semibold text-[#126d91]">Review AI suggestions in the AI Triage section below</a>}</div>
}