import { useState } from 'react';
import { Link } from 'react-router-dom';
export default function WatchlistMatchRow({match,decision,items,busy,onDecide,linkedId}){
 const [editing,setEditing]=useState(false),[changing,setChanging]=useState(false),[rejecting,setRejecting]=useState(false),[reason,setReason]=useState(''),[selected,setSelected]=useState('');
 const linked=linkedId&&items.find(x=>x.id===linkedId),decided=!!decision?.status;
 const decide=async(status,value,reason)=>{if(await onDecide('watchlist_match',status,value,reason)){setEditing(false);setChanging(false);setRejecting(false);setReason('')}};
 const basis=match.confidence>=0.9?'Exact-name match':'Name overlap',strength=match.confidence>=0.9?'High':'Moderate';
 return <div className="rounded-lg border border-[#e3eaf0] p-4 space-y-3">
  <div className="flex flex-wrap justify-between gap-2"><h4 className="text-xs font-bold uppercase tracking-wide text-[#53657b]">Possible Watchlist Match</h4><span className="text-xs text-[#607b8a]">{decided?(linked&&decision.status==='Human Accepted'?'Human Accepted & Linked':linked&&decision.status==='Human Modified'?'Human Modified & Linked':decision.status):'Awaiting human review'}</span></div>
  <p className="text-sm">{match.name}{match.type&&` — ${match.type}`}</p>
  <p className="text-xs text-[#667b8e]">Match basis: {basis} · Match strength: {strength}. {linked?'Analyst-linked entity relationship; this is not a finding.':'Identity remains unconfirmed until human linking.'}</p>
  {decided&&<p className="text-xs text-[#42657a]">Human decision: {decision.status}{decision.status!=='Human Rejected'&&decision.value&&` · ${decision.value}`}{decision.status==='Human Rejected'&&decision.reason&&` · Reason: ${decision.reason}`}. A link is an entity relationship only and does not imply risk, priority, suspicion or a violation.</p>}
  {linked&&decision.status!=='Human Rejected'&&<Link to={`/watchlist/${linked.id}`} className="inline-block text-xs font-semibold text-[#126d91]">View linked Watchlist profile</Link>}
  {decided&&!changing?<div><button type="button" disabled={busy} className="text-xs font-semibold text-[#126d91] hover:underline" onClick={()=>setChanging(true)}>Change decision</button></div>:<div className="flex flex-wrap gap-2"><button type="button" disabled={busy} className="intel-ghost" onClick={()=>decide('Human Accepted')}>ACCEPT & LINK</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>setEditing(true)}>MODIFY</button><button type="button" disabled={busy} className="intel-ghost" onClick={()=>{setEditing(false);setRejecting(true)}}>REJECT</button>{changing&&<button type="button" className="intel-ghost" onClick={()=>{setChanging(false);setEditing(false)}}>Cancel change</button>}</div>}
  {rejecting&&<div className="space-y-2"><label className="intel-label" htmlFor="watchlist-reason">Reason for rejection (required)</label><textarea id="watchlist-reason" className="intel-input" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} rows={2}/><button type="button" disabled={busy||reason.trim().length<5} className="intel-button" onClick={()=>decide('Human Rejected','',reason)}>Save rejection</button> <button type="button" className="intel-ghost" onClick={()=>setRejecting(false)}>Cancel</button></div>}{editing&&<div className="space-y-2"><select className="intel-input" aria-label="Choose corrected watchlist match" value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a watchlist entry</option>{items.map(x=><option key={x.id} value={x.id}>{x.name} — {x.type}</option>)}</select><button type="button" disabled={busy||!selected} className="intel-button" onClick={()=>decide('Human Modified',selected)}>Save & link corrected match</button><button type="button" className="intel-ghost" onClick={()=>setEditing(false)}>Cancel</button></div>}
 </div>;
}