import { createClientFromRequest } from 'npm:@base44/sdk@0.8.49';
import { loadProfile, profile, roleDefinitions, permissionLabels, defaultPermissions, has, allowed, canAdmin, scope, clean, audit, national } from '../../shared/access.ts';
export default async function(req: Request): Promise<Response> {
 try {
  const b=createClientFromRequest(req), u=await b.auth.me(); if(!u) return Response.json({error:'Unauthorized'},{status:401});
  const p=await loadProfile(b,u), {action, data={}, id}=await req.json(); const s=b.asServiceRole.entities;
   if(action==='myAccess')return Response.json({access:{role:p.role,status:p.status,geographic_scope:p.geographic_scope,province:p.province,regency_city:p.regency_city,permissions:p.permissions}});
   if(p.status!=='Active')return Response.json({error:'BAWASLU account access is inactive'},{status:403});
  if(action==='list') { if(!has(p,'view_intelligence')&&!has(p,'manage_watchlist'))return Response.json({error:'Not permitted'},{status:403}); const [items,accounts,relationships,sources,categories]=await Promise.all([s.WatchlistItem.list('-created_date',500),s.SourceAccount.list('-created_date',500),s.EntityRelationship.list('-created_date',500),s.DataSource.list('-created_date',500),s.IssueCategory.list('sort_order',100)]); const visible=scope(p,items); return Response.json({items:visible,accounts:accounts.filter(a=>visible.some(w=>w.id===a.watchlist_id)),relationships:relationships.filter(r=>visible.some(w=>w.id===r.from_id)&&visible.some(w=>w.id===r.to_id)),sources:scope(p,sources),categories}); }
  if(action==='createWatchlist') { if(!has(p,'manage_watchlist')) return Response.json({error:'Not permitted'},{status:403}); const name=clean(data.name,180), type=clean(data.type,100); if(!name||!type||!allowed(p,data)) return Response.json({error:'Name, type and permitted location required'},{status:400}); const item=await s.WatchlistItem.create({name,type,description:clean(data.description),province:clean(data.province,100),regency_city:clean(data.regency_city,100),related_election:clean(data.related_election,100),related_entity:clean(data.related_entity,180),related_topics:Array.isArray(data.related_topics)?data.related_topics.slice(0,20).map(x=>clean(x,100)):[],priority:clean(data.priority,20)||'Medium',status:clean(data.status,30)||'Active',notes:clean(data.notes)}); await audit(b,p,'WatchlistItem',item.id,'CREATED',{name:{new:name}}); return Response.json({item}); }
  if(action==='addAccount') { if(!has(p,'manage_watchlist')) return Response.json({error:'Not permitted'},{status:403}); const parent=await s.WatchlistItem.get(id); if(!parent||!allowed(p,parent)) return Response.json({error:'Not found'},{status:404}); let url; try { url=new URL(data.url); if(!['http:','https:'].includes(url.protocol)) throw Error(); } catch {return Response.json({error:'Enter a valid public URL'},{status:400});} const account=await s.SourceAccount.create({watchlist_id:id,platform:clean(data.platform,60),url:url.href,handle:clean(data.handle,120),province:parent.province,regency_city:parent.regency_city}); await audit(b,p,'WatchlistItem',id,'ACCOUNT_ADDED',{url:{new:url.href}}); return Response.json({account}); }
  if(action==='addRelationship') { if(!has(p,'manage_watchlist')) return Response.json({error:'Not permitted'},{status:403}); const from=await s.WatchlistItem.get(id), to=await s.WatchlistItem.get(data.to_id); if(!from||!to||!allowed(p,from)||!allowed(p,to)) return Response.json({error:'Not found'},{status:404}); const relationship=await s.EntityRelationship.create({from_id:id,to_id:to.id,relationship_type:clean(data.relationship_type,100),province:from.province}); await audit(b,p,'WatchlistItem',id,'RELATIONSHIP_ADDED',{to:{new:to.id}}); return Response.json({relationship}); }
  if(action==='addSource') { if(!canAdmin(p)||!allowed(p,data)) return Response.json({error:'Not permitted'},{status:403}); const type=clean(data.source_type,80); if(!['MANUAL_LINK','MANUAL_ENTRY','FILE_UPLOAD','INTERNAL_BAWASLU','OFFICIAL_SOURCE'].includes(type)) return Response.json({error:'Invalid source type'},{status:400}); const source=await s.DataSource.create({name:clean(data.name,180),source_type:type,description:clean(data.description),status:'ACTIVE',province:clean(data.province,100),regency_city:clean(data.regency_city,100)}); await audit(b,p,'DataSource',source.id,'CREATED'); return Response.json({source}); }
  if(action==='category') { if(p.role!=='National Administrator'||!has(p,'administration')) return Response.json({error:'Not permitted'},{status:403}); const name=clean(data.name,100); if(!name) return Response.json({error:'Name required'},{status:400});const existing=await s.IssueCategory.list();if(existing.some(x=>x.name.toLowerCase()===name.toLowerCase()))return Response.json({error:'Category already exists'},{status:400}); const category=await s.IssueCategory.create({name,active:true,sort_order:Date.now()}); await audit(b,p,'IssueCategory',category.id,'CREATED',{name:{previous:null,new:name},active:{previous:null,new:true}}); return Response.json({category}); }
   if(action==='updateCategory') {if(p.role!=='National Administrator'||!has(p,'administration'))return Response.json({error:'Not permitted'},{status:403});const category=await s.IssueCategory.get(id);if(!category)return Response.json({error:'Not found'},{status:404});const name=clean(data.name,100);if(!name||typeof data.active!=='boolean')return Response.json({error:'Name and status required'},{status:400});const others=await s.IssueCategory.list();if(others.some(x=>x.id!==id&&x.name.toLowerCase()===name.toLowerCase()))return Response.json({error:'Category already exists'},{status:400});await s.IssueCategory.update(id,{name,active:data.active});await audit(b,p,'IssueCategory',id,'CATEGORY_CHANGED',{name:{previous:category.name,new:name},active:{previous:category.active,new:data.active}});return Response.json({ok:true});}
  if(action==='users') { if(!canAdmin(p)) return Response.json({error:'Not permitted'},{status:403}); const [users,grants]=await Promise.all([s.User.list('-created_date',500),s.AccessGrant.list('-created_date',500)]); const byId=new Map(grants.map(g=>[g.user_id,g])); return Response.json({users:users.map(x=>{const g=byId.get(x.id),a=profile(x,g);return {id:x.id,full_name:x.full_name,email:x.email,access_role:a.role,province:a.province,regency_city:a.regency_city,geographic_scope:a.geographic_scope,permissions:a.permissions,status:a.status,updated_date:g?.updated_date||g?.created_date||'',platform_admin:x.role==='admin'};}).filter(x=>national.includes(p.role)||allowed(p,x)&&!national.includes(x.access_role)),administrator_role:p.role,administrator_province:p.province,roles:roleDefinitions,permission_labels:permissionLabels}); }
  if(action==='accessHistory') {if(!canAdmin(p))return Response.json({error:'Not permitted'},{status:403});const target=await s.User.get(id),grant=(await s.AccessGrant.filter({user_id:id}))[0];if(!target||!national.includes(p.role)&&!allowed(p,profile(target,grant)))return Response.json({error:'Not found'},{status:404});const events=await s.AuditEvent.filter({subject_type:'User',subject_id:id},'-created_date',50);return Response.json({events});}
  if(action==='setUser') { if(!canAdmin(p)) return Response.json({error:'Not permitted'},{status:403}); const target=await s.User.get(id); if(!target)return Response.json({error:'Not found'},{status:404}); const current=(await s.AccessGrant.filter({user_id:id}))[0],previous=profile(target,current); const role=clean(data.access_role,80),definition=roleDefinitions[role]; if(!definition)return Response.json({error:'Invalid role'},{status:400}); const geographic_scope=definition.scope==='Selectable'?clean(data.geographic_scope,30):definition.scope; if(!['Nationwide','Province','Regency/City'].includes(geographic_scope))return Response.json({error:'Choose a geographic scope'},{status:400}); const province=geographic_scope==='Nationwide'?'':clean(data.province,100),regency_city=geographic_scope==='Nationwide'?'':clean(data.regency_city,100); if(geographic_scope!=='Nationwide'&&!province)return Response.json({error:'Province required'},{status:400}); if(geographic_scope==='Regency/City'&&!regency_city)return Response.json({error:'Regency / City required'},{status:400}); const status=data.status==='Inactive'?'Inactive':data.status==='Active'?'Active':null;if(!status)return Response.json({error:'Select an account status'},{status:400}); const permissions={};for(const key of Object.keys(permissionLabels)){if(typeof data.permissions?.[key]!=='boolean')return Response.json({error:'Choose all functional permissions'},{status:400});permissions[key]=data.permissions[key];if(permissions[key]&&!has(p,key)&&!national.includes(p.role))return Response.json({error:'Cannot grant authority you do not hold'},{status:403});} const next={access_role:role,geographic_scope,province,regency_city,permissions,status}; if(!national.includes(p.role)&&(!allowed(p,previous)||!allowed(p,next)||national.includes(role)||target.id===p.id))return Response.json({error:'Assignment outside your jurisdiction'},{status:403}); const prior={access_role:previous.role,geographic_scope:previous.geographic_scope,province:previous.province,regency_city:previous.regency_city,permissions:previous.permissions,status:previous.status}; const saved=current?await s.AccessGrant.update(current.id,next):await s.AccessGrant.create({user_id:id,...next});await audit(b,p,'User',id,'USER_ACCESS_UPDATED',{affected_user:{previous:target.email,new:target.email},assignment:{previous:prior,new:next}});return Response.json({ok:true,user:{id,full_name:target.full_name,email:target.email,...next,updated_date:saved.updated_date||new Date().toISOString(),platform_admin:target.role==='admin'}}); }
  return Response.json({error:'Unknown action'},{status:400});
 } catch(e) { if(e.code==='ACCESS_RESOLUTION_ERROR')return Response.json({error:'BAWASLU access could not be resolved. Please retry.',code:e.code},{status:503}); return Response.json({error:e.message},{status:500}); }
}