import { useState } from 'react';
import { Send } from 'lucide-react';
import { base44 } from '@/api/base44Client';
import AssistantRecords from '@/components/intel/AssistantRecords';
import AssistantAnswer from '@/components/intel/AssistantAnswer';
import { useLanguage } from '@/lib/LanguageContext';
const starterKeys=['starter_latest_validated','starter_main_issues','starter_last_7_days','starter_campaign_issues','starter_locations','starter_high_priority','starter_campaign_materials','starter_unverified','starter_today'];
export default function IntelligenceAssistant(){
  const {t}=useLanguage();
  const starters=starterKeys.map(t);
  const [question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  async function ask(text){const q=text.trim();if(!q||busy)return;setBusy(true);setError('');setQuestion('');setMessages(old=>[...old,{role:'user',text:q}]);try{const previousQuestion=[...messages].reverse().find(m=>m.role==='user')?.text||'';const response=await base44.functions.invoke('intelligenceAssistant',{question:q,previousQuestion});setMessages(old=>[...old,{role:'assistant',text:response.data.answer,records:response.data.records||[],provider:response.data.provider,grounding:response.data.grounding}]);}catch(e){setError(e.response?.data?.error||t('assistant_unavailable'));setMessages(old=>old.slice(0,-1));setQuestion(q)}finally{setBusy(false)}}
  return <div className="max-w-4xl mx-auto space-y-5"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#9a7e49] mb-2">{t('assistant_read_only')}</p><h1 className="intel-heading">{t('intelligence_assistant')}</h1><p className="text-sm font-medium text-[#29445d] mt-2">{t('assistant_tagline')}</p><p className="text-sm text-[#617789] mt-2">{t('assistant_intro')}</p></div><div className="flex justify-end"><button type="button" className="intel-ghost" disabled={busy||!messages.length} onClick={()=>{setMessages([]);setQuestion('');setError('')}}>{t('new_conversation')}</button></div><div className="intel-card p-5 md:p-7 space-y-5" aria-live="polite">{!messages.length&&<div><p className="text-sm font-semibold mb-3">{t('try_asking')}</p><div className="flex flex-wrap gap-2">{starters.map(s=><button type="button" key={s} disabled={busy} onClick={()=>ask(s)} className="intel-ghost text-left text-xs">{s}</button>)}</div></div>}{messages.map((m,i)=><div key={i} className={m.role==='user'?'flex justify-end':'flex justify-start'}><div className={m.role==='user'?'max-w-[90%] rounded-xl bg-[#153b57] text-white px-4 py-3 text-sm':'w-full rounded-xl bg-[#f5f7fa] border border-[#e4e9ef] p-4 text-sm'}>{m.role==='assistant'?<AssistantAnswer text={m.text}/>:<p className="whitespace-pre-line leading-6">{m.text}</p>}{m.role==='assistant'&&<>{m.provider&&<p className={`mt-4 rounded-lg border px-3 py-2 text-xs ${m.provider.mode==='OPENAI_GROUNDED'?'border-sky-200 bg-sky-50 text-[#315f76]':'border-amber-200 bg-amber-50 text-[#7b622c]'}`}><strong>{m.provider.mode==='OPENAI_GROUNDED'?t('grounded_ai_answer'):t('safe_fallback')}</strong>{m.provider.model?` · ${m.provider.model}`:''}{m.grounding?` · ${m.grounding.supporting_count} supporting record(s) · ${m.grounding.date_basis_label||'No special date filter'}`:''}</p>}<AssistantRecords records={m.records}/></>}</div></div>)}{busy&&<p role="status" className="text-sm text-[#617789]">{t('reviewing_records')}</p>}{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div><form onSubmit={e=>{e.preventDefault();ask(question)}} className="intel-card p-3 flex gap-2"><input aria-label={t('assistant_question_aria')} className="intel-input flex-1" maxLength={400} placeholder={t('assistant_placeholder')} value={question} onChange={e=>setQuestion(e.target.value)}/><button className="intel-button" disabled={busy||!question.trim()}><Send size={16}/><span className="hidden sm:inline">{t('send')}</span></button></form><p className="text-xs text-[#8192a3]">{t('assistant_footer')}</p></div>;
}