import { Link, useParams } from 'react-router-dom';
import { useRegistry } from '@/components/intel/useIntel';
import { Notice } from '@/components/intel/Fields';
import ActorIntelligence from '@/components/intel/ActorIntelligence';
export default function WatchlistProfile(){
 const {id}=useParams(),{items,accounts,relationships,loading,error}=useRegistry();
 if(loading)return <p className="text-sm text-[#77899b]">Loading Watchlist profile...</p>;
 const item=items.find(x=>x.id===id);
 if(!item)return <Notice error={error||'Watchlist profile unavailable in your jurisdiction.'}/>;
 return <div className="space-y-5 max-w-4xl"><Link to="/watchlist" className="text-sm text-[#126d91]">← Watchlist</Link><section className="intel-card p-6 space-y-5"><div><p className="text-xs uppercase font-bold text-[#53657b]">Watchlist profile · Entity relationship only</p><h1 className="intel-heading mt-2">{item.name}</h1><p className="text-sm text-[#607b8a]">{item.type}</p></div><p className="text-sm">{item.description||'No description provided.'}</p><div className="grid sm:grid-cols-2 gap-4 text-sm">{[['Province',item.province],['Regency / City',item.regency_city],['Related election',item.related_election],['Related entity',item.related_entity],['Topics',item.related_topics?.join(', ')],['Monitoring priority',item.priority],['Monitoring status',item.status],['Notes',item.notes]].map(([label,value])=><div key={label}><span className="intel-label">{label}</span><p className="whitespace-pre-wrap">{value||'—'}</p></div>)}</div><div><span className="intel-label">Public accounts & URLs</span>{accounts.filter(a=>a.watchlist_id===id).map(a=><a key={a.id} href={a.url} target="_blank" rel="noreferrer" className="block text-sm text-[#126d91] break-all">{a.platform||'Web'} · {a.handle||a.url}</a>)}{!accounts.some(a=>a.watchlist_id===id)&&<p className="text-sm">None recorded.</p>}</div><div><span className="intel-label">Registry relationships</span>{relationships.filter(r=>r.from_id===id).map(r=><p key={r.id} className="text-sm">{r.relationship_type} · {items.find(w=>w.id===r.to_id)?.name||'Watchlist entry'}</p>)}{!relationships.some(r=>r.from_id===id)&&<p className="text-sm">None recorded.</p>}</div><p className="text-xs text-[#607b8a]">A Watchlist link identifies an entity relationship only. It does not establish identity, risk, suspicion, a violation, priority, scoring, or enforcement grounds.</p></section><ActorIntelligence actorId={id} accounts={accounts}/></div>
}