import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext=createContext(null);

const translations={
  en:{
    workspace:'Workspace',future_modules:'Future modules',soon:'SOON',
    home:'Home',watchlist:'Watchlist',social_listening:'Social Listening',intelligence_inbox:'Intelligence Inbox',
    intelligence_assistant:'BAWASLU Intelligence Assistant',add_intelligence:'Add Intelligence',data_sources:'Data Sources',
    validation:'Validation',administration:'Administration',intelligence_command:'Intelligence Command',
    secure_workspace:'Secure workspace',authorized_user:'Authorized user',
    election_supervision_intelligence:'Election supervision / Intelligence',add:'Add',
    loading_access:'Loading BAWASLU access...',inactive_access:'Your BAWASLU access is inactive.',select:'Select',

    workspace_overview:'Workspace Overview',
    intelligence_situation:'Intelligence Situation',
    home_intro:'Operational overview of the existing BAWASLU workspace and the items that need attention now.',
    operational_metrics:'Operational metrics',
    authorized_scope_note:'Counts are limited to intelligence records available within your authorized scope.',
    open:'Open',
    pending_intelligence_review:'Pending Intelligence Review',
    pending_intelligence_detail:'Needs human review or validation.',
    validated_intelligence:'Validated Intelligence',
    validated_intelligence_detail:'Human-validated relevant intelligence.',
    unverified_evidence:'UNVERIFIED Evidence',
    unverified_evidence_detail:'Source verification is still pending.',
    jurisdiction_unresolved:'Jurisdiction Unresolved',
    jurisdiction_unresolved_detail:'Needs human jurisdiction confirmation.',
    ai_triage_awaiting_review:'AI Triage Awaiting Review',
    ai_triage_detail:'Generated suggestions still need analyst decisions.',
    social_review_queue:'Social Review Queue',
    social_review_detail:'Stored results awaiting human disposition.',
    attention_now:'What needs attention now',
    attention_rank_note:'Ranked by geographic mismatch, AI review, human review, jurisdiction and priority.',
    open_inbox:'Open inbox',
    geographic_mismatch:'Geographic mismatch',
    ai_triage_review:'AI triage review',
    pending_human_review:'Pending human review',
    critical_priority:'Critical priority',
    high_priority:'High priority',
    jurisdiction_not_confirmed:'Jurisdiction not confirmed',
    validated_monitoring:'Validated intelligence & monitoring queues',
    validated_monitoring_note:'Compact management view of validated intelligence, Watchlist state and stored Social Listening review work.',
    latest_validated:'Latest validated intelligence',
    view_all:'View all',
    watchlist_summary_unavailable:'Watchlist summary unavailable. The rest of Home remains available.',
    loading_watchlist_summary:'Loading Watchlist summary...',
    social_queue_unavailable:'Social Listening queue status is temporarily unavailable.',
    no_socialcrawl_search:'No SocialCrawl search was triggered.',
    loading_social_queue:'Loading stored Social Listening queue...',
    active:'Active',under_review:'Under Review',inactive:'Inactive',
    discovered:'Discovered',relevant:'Relevant',monitor:'Monitor',
    validated_label:'Validated',source_label:'Source',verification_label:'Verification',
    audit_updated:'Updated',audit_created:'Created',audit_source_account_updated:'Source account updated',audit_source_account_added:'Source account added',audit_source_account_removed:'Source account removed',audit_relationship_added:'Relationship added',audit_relationship_removed:'Relationship removed',audit_source_recovered:'Source recovered',audit_geographic_reviewed:'Geographic mismatch reviewed',audit_watchlist_updated:'Watchlist updated',audit_reviewed:'Reviewed',audit_accepted:'Accepted',audit_modified:'Modified',audit_rejected:'Rejected',audit_linked:'Linked',
    human_label:'Human',ai_triage_label:'AI Triage',potential_duplicate_status:'Potential Duplicate',
    recent_activity:'Recent activity',
    recent_activity_note:'Latest recorded workspace actions. Activity failure does not block the operational dashboard.',
    recent_activity_unavailable:'Recent activity is temporarily unavailable.',
    no_recent_activity:'No recent activity yet.',
    system:'System',
    no_immediate_attention:'No intelligence currently requires immediate attention.',
    no_validated_scope:'No validated intelligence in your authorized scope yet.',
    untitled_intelligence:'Untitled intelligence',
    source_not_recorded:'Source not recorded',
    confirmed:'Confirmed',national:'National',

    collection_triage:'Collection / Triage',
    all_intelligence:'All intelligence',
    pending_review:'Pending Review',
    validated:'Validated',
    unverified:'UNVERIFIED',
    ai_triage_waiting:'AI Triage Awaiting Review',
    search_placeholder:'Search keywords, ID, entity or location...',
    all_prefix:'All',
    sort_recently_updated:'Recently updated',
    sort_newest_created:'Newest created',
    sort_oldest_created:'Oldest created',
    sort_highest_priority:'Highest priority',
    sort_intelligence_id:'Intelligence ID',
    view:'View',
    clear_all_filters:'Clear all filters',
    loading_intelligence:'Loading intelligence...',
    submitted_jurisdiction:'Submitted for national jurisdiction resolution. Regional users cannot access the record until it is confirmed.',
    match:'match',matches:'matches',
    records_authorized_scope:'records in authorized scope',
    record_authorized_scope:'record in authorized scope',
    filter_search:'Search',filter_date:'Date',filter_entity:'Entity',filter_verification:'Verification',
    filter_review_status:'Review status',filter_priority:'Priority',filter_province:'Province',
    filter_regency_city:'Regency / City',filter_platform:'Platform',filter_evidence_type:'Evidence type',
    filter_reviewer:'Reviewer',filter_source_type:'Source type',filter_supervision_signal:'Supervision signal',
    location:'Location',evidence:'Evidence',priority:'Priority',reviewer:'Reviewer',updated:'Updated',
    unassigned:'Unassigned',no_related_entity:'No related entity',
    source_type_not_recorded:'Source type not recorded',
    jurisdiction_unresolved_short:'Jurisdiction unresolved',
    geographic_review_required:'Geographic mismatch review required',
    no_match_current_filters:'No intelligence matches the current view and filters.',
    not_classified:'Not classified'
    ,result:'result',results:'results',
    monitoring_registry:'Monitoring registry',watchlist_intro:'Human-managed entities, issues, locations, relationships and public source accounts used across the workspace.',
    add_watchlist_item:'Add Watchlist Item',editing_watchlist_item:'Editing existing watchlist item',create_watchlist_item:'Create watchlist item',edit_prefix:'Edit',watchlist_item:'Watchlist item',new_watchlist_item:'New watchlist item',edit_watchlist_help:'Save changes to update this existing record. Cancel returns to the watchlist without changing it.',
    name:'Name',type:'Type',monitoring_priority:'Monitoring Priority',province:'Province',regency_city:'Regency / City',related_election:'Related Election',related_entity:'Related Entity',related_topics:'Related Topics (comma-separated)',monitoring_status:'Monitoring Status',description:'Description',notes:'Notes',
    saving:'Saving...',save_changes:'Save changes',create_item:'Create item',cancel:'Cancel',search_watchlist:'Search name, type, topic or geography...',all_statuses:'All statuses',all_types:'All types',all_priorities:'All priorities',all_geographies:'All geographies',loading_watchlist:'Loading watchlist...',
    no_description:'No description provided.',nationwide:'Nationwide',election_not_specified:'Election not specified',created:'Created',view_related_intelligence:'View related intelligence',edit:'Edit',activate:'Activate',set_under_review:'Set Under Review',deactivate:'Deactivate',
    public_accounts_urls:'PUBLIC ACCOUNTS & URLS',no_public_account:'No registered public account / URL.',public_url:'Public URL',handle:'Handle',save_account:'Save account',add_account:'Add account',add_public_account:'+ Add public URL / account',
    related_watchlist_items:'RELATED WATCHLIST ITEMS',no_recorded_relationship:'No recorded relationship.',select_watchlist_item:'Select watchlist item',select_relationship_type:'Select relationship type',link_items:'Link items',link_watchlist_item:'+ Link watchlist item',remove_public_confirm:'Remove this public account / URL from the watchlist?',remove_relationship_confirm:'Remove this relationship?',no_watchlist_filter_match:'No watchlist items match the current filters.',
    watchlist_profile_loading:'Loading Watchlist profile...',watchlist_profile_unavailable:'Watchlist profile unavailable in your jurisdiction.',watchlist_profile_label:'Watchlist profile · Entity relationship only',topics:'Topics',public_accounts:'Public accounts & URLs',registry_relationships:'Registry relationships',none_recorded:'None recorded.',watchlist_entry:'Watchlist entry',watchlist_disclaimer:'A Watchlist link identifies an entity relationship only. It does not establish identity, risk, suspicion, a violation, priority, scoring, or enforcement grounds.',
    back_inbox:'Intelligence Inbox',record_display_error:'Record display error',record_display_error_help:'This intelligence record could not be displayed safely. The record remains stored; return to the inbox and try again after refresh.',unexpected_display_error:'Unexpected display error',return_inbox:'Return to Intelligence Inbox',refresh_record:'Refresh record',loading_record:'Loading intelligence record...',access_denied:'Access Denied',access_denied_help:'You do not have permission to access this intelligence record. The record may be outside your assigned jurisdiction or unavailable under your current access level.',intelligence_record:'Intelligence record',edit_record:'Edit record',
    correct_record:'Correct record · human edit',headline:'Headline',source_publisher:'Source / Publisher',author:'Author',related_topics_label:'Related Topics',assigned_reviewer:'Assigned Reviewer',original_preserved_help:'Original source text, language, URL and uploaded files are preserved as submitted; attach additional evidence rather than replacing them.',english_translation:'English Translation',ai_unchanged_help:'AI suggestions remain unchanged. Record human corrections in analyst notes.',analyst_notes:'Analyst Notes',save_corrections:'Save corrections',
    original_source:'Original Source',what_source_says:'WHAT THE SOURCE SAYS',no_source_text:'No source text entered. Consult the original URL or attached material.',view_full_source:'View full retrieved source material · preserved evidence',full_source_help:'The article body above may be cleaned for readability and AI triage. The full retrieved source is preserved here and is never silently replaced.',original_url:'Original URL',open_original_source:'Open original source',author_account:'Author / Account',platform_publisher:'Platform / Publisher',published:'Published',original_language:'Original Language',collected:'Collected',translation:'Translation',no_translation:'No English translation recorded.',
    evidence_assessment:'Evidence Assessment',evidence_type:'Evidence Type',verification_status:'Verification Status',evidence_explain:'OBSERVED describes what the source represents; UNVERIFIED means independent source verification has not been completed. Human validation does not establish a violation.',mark_verified:'Mark source HUMAN VERIFIED',
    legacy_analysis:'Legacy Analysis (if recorded)',ai_suggestion_not_finding:'AI SUGGESTION · NOT A FINDING',no_ai_analysis:'No AI analysis accepted.',review_ai_suggestions:'REVIEW AI SUGGESTIONS',supporting_evidence:'Supporting Evidence',no_files:'No files attached.',attach_supporting_material:'Attach original supporting material (private)',evidence_description:'Evidence description',upload_evidence:'Upload evidence',
    related_intelligence:'Related Intelligence',entities:'Entities',human_linked_watchlist:'Human-linked Watchlist',watchlist_relationship_only:'Watchlist entry · Entity relationship only; no risk, violation or priority inferred.',view_watchlist_profile:'View Watchlist Profile',human_review:'Human Review',decision:'Decision',timestamp:'Timestamp',no_review_notes:'No review notes yet.',validation_decision:'Validation Decision',review_notes:'Review Notes',geographic_pending_block:'Geographic mismatch review is pending. Final validation is blocked until the jurisdiction decision above is completed.',triage_pending_block:'Complete review of all generated AI Triage suggestions before final validation.',record_human_decision:'Record human decision',restricted_reviewers:'Restricted to authorized reviewers.'
  },

  id:{
    workspace:'Ruang Kerja',future_modules:'Modul Mendatang',soon:'SEGERA',
    home:'Beranda',watchlist:'Daftar Pantauan',social_listening:'Pemantauan Media Sosial',intelligence_inbox:'Kotak Masuk Intelijen',
    intelligence_assistant:'Asisten Intelijen BAWASLU',add_intelligence:'Tambah Intelijen',data_sources:'Sumber Data',
    validation:'Validasi',administration:'Administrasi',intelligence_command:'Komando Intelijen',
    secure_workspace:'Ruang kerja aman',authorized_user:'Pengguna berwenang',
    election_supervision_intelligence:'Pengawasan Pemilu / Intelijen',add:'Tambah',
    loading_access:'Memuat akses BAWASLU...',inactive_access:'Akses BAWASLU Anda tidak aktif.',select:'Pilih',

    workspace_overview:'Ikhtisar Ruang Kerja',
    intelligence_situation:'Situasi Intelijen',
    home_intro:'Ikhtisar operasional ruang kerja BAWASLU dan hal-hal yang memerlukan perhatian saat ini.',
    operational_metrics:'Metrik Operasional',
    authorized_scope_note:'Jumlah dibatasi pada catatan intelijen yang tersedia dalam cakupan akses Anda.',
    open:'Buka',
    pending_intelligence_review:'Intelijen Menunggu Peninjauan',
    pending_intelligence_detail:'Memerlukan peninjauan atau validasi manusia.',
    validated_intelligence:'Intelijen Tervalidasi',
    validated_intelligence_detail:'Intelijen relevan yang telah divalidasi manusia.',
    unverified_evidence:'Bukti BELUM DIVERIFIKASI',
    unverified_evidence_detail:'Verifikasi sumber masih menunggu.',
    jurisdiction_unresolved:'Yurisdiksi Belum Ditentukan',
    jurisdiction_unresolved_detail:'Memerlukan konfirmasi yurisdiksi oleh manusia.',
    ai_triage_awaiting_review:'Triage AI Menunggu Peninjauan',
    ai_triage_detail:'Saran yang dihasilkan masih memerlukan keputusan analis.',
    social_review_queue:'Antrean Tinjauan Sosial',
    social_review_detail:'Hasil tersimpan menunggu keputusan manusia.',
    attention_now:'Yang Perlu Diperhatikan Sekarang',
    attention_rank_note:'Diurutkan berdasarkan ketidaksesuaian geografis, tinjauan AI, tinjauan manusia, yurisdiksi, dan prioritas.',
    open_inbox:'Buka Kotak Masuk',
    geographic_mismatch:'Ketidaksesuaian geografis',
    ai_triage_review:'Tinjauan triage AI',
    pending_human_review:'Menunggu tinjauan manusia',
    critical_priority:'Prioritas kritis',
    high_priority:'Prioritas tinggi',
    jurisdiction_not_confirmed:'Yurisdiksi belum dikonfirmasi',
    validated_monitoring:'Intelijen Tervalidasi & Antrean Pemantauan',
    validated_monitoring_note:'Tampilan ringkas untuk intelijen tervalidasi, status Daftar Pantauan, dan pekerjaan tinjauan Pemantauan Media Sosial yang tersimpan.',
    latest_validated:'Intelijen Tervalidasi Terbaru',
    view_all:'Lihat Semua',
    watchlist_summary_unavailable:'Ringkasan Daftar Pantauan sementara tidak tersedia. Bagian Beranda lainnya tetap tersedia.',
    loading_watchlist_summary:'Memuat ringkasan Daftar Pantauan...',
    social_queue_unavailable:'Status antrean Pemantauan Media Sosial sementara tidak tersedia.',
    no_socialcrawl_search:'Tidak ada pencarian SocialCrawl yang dijalankan.',
    loading_social_queue:'Memuat antrean Pemantauan Media Sosial yang tersimpan...',
    active:'Aktif',under_review:'Dalam Peninjauan',inactive:'Tidak Aktif',
    discovered:'Ditemukan',relevant:'Relevan',monitor:'Pantau',
    validated_label:'Divalidasi',source_label:'Sumber',verification_label:'Verifikasi',
    audit_updated:'Diperbarui',audit_created:'Dibuat',audit_source_account_updated:'Akun sumber diperbarui',audit_source_account_added:'Akun sumber ditambahkan',audit_source_account_removed:'Akun sumber dihapus',audit_relationship_added:'Hubungan ditambahkan',audit_relationship_removed:'Hubungan dihapus',audit_source_recovered:'Sumber dipulihkan',audit_geographic_reviewed:'Ketidaksesuaian geografis ditinjau',audit_watchlist_updated:'Daftar Pantauan diperbarui',audit_reviewed:'Ditinjau',audit_accepted:'Diterima',audit_modified:'Diubah',audit_rejected:'Ditolak',audit_linked:'Ditautkan',
    human_label:'Manusia',ai_triage_label:'Triage AI',potential_duplicate_status:'Potensi Duplikat',
    recent_activity:'Aktivitas Terbaru',
    recent_activity_note:'Tindakan terbaru yang tercatat di ruang kerja. Kegagalan aktivitas tidak memblokir dasbor operasional.',
    recent_activity_unavailable:'Aktivitas terbaru sementara tidak tersedia.',
    no_recent_activity:'Belum ada aktivitas terbaru.',
    system:'Sistem',
    no_immediate_attention:'Tidak ada intelijen yang saat ini memerlukan perhatian segera.',
    no_validated_scope:'Belum ada intelijen tervalidasi dalam cakupan akses Anda.',
    untitled_intelligence:'Intelijen Tanpa Judul',
    source_not_recorded:'Sumber belum tercatat',
    confirmed:'Dikonfirmasi',national:'Nasional',

    collection_triage:'Pengumpulan / Triage',
    all_intelligence:'Semua Intelijen',
    pending_review:'Menunggu Peninjauan',
    validated:'Tervalidasi',
    unverified:'BELUM DIVERIFIKASI',
    ai_triage_waiting:'Triage AI Menunggu Peninjauan',
    search_placeholder:'Cari kata kunci, ID, entitas, atau lokasi...',
    all_prefix:'Semua',
    sort_recently_updated:'Terakhir Diperbarui',
    sort_newest_created:'Terbaru Dibuat',
    sort_oldest_created:'Terlama Dibuat',
    sort_highest_priority:'Prioritas Tertinggi',
    sort_intelligence_id:'ID Intelijen',
    view:'Tampilan',
    clear_all_filters:'Hapus Semua Filter',
    loading_intelligence:'Memuat intelijen...',
    submitted_jurisdiction:'Diajukan untuk penyelesaian yurisdiksi nasional. Pengguna regional tidak dapat mengakses catatan hingga dikonfirmasi.',
    match:'cocok',matches:'cocok',
    records_authorized_scope:'catatan dalam cakupan akses',
    record_authorized_scope:'catatan dalam cakupan akses',
    filter_search:'Pencarian',filter_date:'Tanggal',filter_entity:'Entitas',filter_verification:'Verifikasi',
    filter_review_status:'Status Peninjauan',filter_priority:'Prioritas',filter_province:'Provinsi',
    filter_regency_city:'Kabupaten / Kota',filter_platform:'Platform',filter_evidence_type:'Jenis Bukti',
    filter_reviewer:'Peninjau',filter_source_type:'Jenis Sumber',filter_supervision_signal:'Sinyal Pengawasan',
    location:'Lokasi',evidence:'Bukti',priority:'Prioritas',reviewer:'Peninjau',updated:'Diperbarui',
    unassigned:'Belum Ditugaskan',no_related_entity:'Tidak ada entitas terkait',
    source_type_not_recorded:'Jenis sumber belum tercatat',
    jurisdiction_unresolved_short:'Yurisdiksi belum ditentukan',
    geographic_review_required:'Tinjauan ketidaksesuaian geografis diperlukan',
    no_match_current_filters:'Tidak ada intelijen yang cocok dengan tampilan dan filter saat ini.',
    not_classified:'Belum Diklasifikasikan'
    ,result:'hasil',results:'hasil',
    monitoring_registry:'Registri Pemantauan',watchlist_intro:'Entitas, isu, lokasi, hubungan, dan akun sumber publik yang dikelola manusia dan digunakan di seluruh ruang kerja.',
    add_watchlist_item:'Tambah Item Pantauan',editing_watchlist_item:'Mengedit item pantauan',create_watchlist_item:'Buat item pantauan',edit_prefix:'Edit',watchlist_item:'Item pantauan',new_watchlist_item:'Item pantauan baru',edit_watchlist_help:'Simpan perubahan untuk memperbarui catatan ini. Batal akan kembali ke daftar pantauan tanpa mengubahnya.',
    name:'Nama',type:'Jenis',monitoring_priority:'Prioritas Pemantauan',province:'Provinsi',regency_city:'Kabupaten / Kota',related_election:'Pemilu Terkait',related_entity:'Entitas Terkait',related_topics:'Topik Terkait (dipisahkan koma)',monitoring_status:'Status Pemantauan',description:'Deskripsi',notes:'Catatan',
    saving:'Menyimpan...',save_changes:'Simpan perubahan',create_item:'Buat item',cancel:'Batal',search_watchlist:'Cari nama, jenis, topik, atau wilayah...',all_statuses:'Semua status',all_types:'Semua jenis',all_priorities:'Semua prioritas',all_geographies:'Semua wilayah',loading_watchlist:'Memuat daftar pantauan...',
    no_description:'Tidak ada deskripsi.',nationwide:'Nasional',election_not_specified:'Pemilu belum ditentukan',created:'Dibuat',view_related_intelligence:'Lihat intelijen terkait',edit:'Edit',activate:'Aktifkan',set_under_review:'Tandai Dalam Peninjauan',deactivate:'Nonaktifkan',
    public_accounts_urls:'AKUN PUBLIK & URL',no_public_account:'Belum ada akun publik / URL terdaftar.',public_url:'URL Publik',handle:'Handle',save_account:'Simpan akun',add_account:'Tambah akun',add_public_account:'+ Tambah URL / akun publik',
    related_watchlist_items:'ITEM DAFTAR PANTAUAN TERKAIT',no_recorded_relationship:'Belum ada hubungan tercatat.',select_watchlist_item:'Pilih item daftar pantauan',select_relationship_type:'Pilih jenis hubungan',link_items:'Hubungkan item',link_watchlist_item:'+ Hubungkan item daftar pantauan',remove_public_confirm:'Hapus akun publik / URL ini dari daftar pantauan?',remove_relationship_confirm:'Hapus hubungan ini?',no_watchlist_filter_match:'Tidak ada item daftar pantauan yang cocok dengan filter saat ini.',
    watchlist_profile_loading:'Memuat profil Daftar Pantauan...',watchlist_profile_unavailable:'Profil Daftar Pantauan tidak tersedia dalam yurisdiksi Anda.',watchlist_profile_label:'Profil Daftar Pantauan · Hanya hubungan entitas',topics:'Topik',public_accounts:'Akun Publik & URL',registry_relationships:'Hubungan Registri',none_recorded:'Belum ada.',watchlist_entry:'Item Daftar Pantauan',watchlist_disclaimer:'Tautan Daftar Pantauan hanya menunjukkan hubungan entitas. Tautan ini tidak menetapkan identitas, risiko, kecurigaan, pelanggaran, prioritas, penilaian, atau dasar penegakan.',
    back_inbox:'Kotak Masuk Intelijen',record_display_error:'Kesalahan tampilan catatan',record_display_error_help:'Catatan intelijen ini tidak dapat ditampilkan dengan aman. Catatan tetap tersimpan; kembali ke kotak masuk dan coba lagi setelah memuat ulang.',unexpected_display_error:'Kesalahan tampilan tak terduga',return_inbox:'Kembali ke Kotak Masuk Intelijen',refresh_record:'Muat ulang catatan',loading_record:'Memuat catatan intelijen...',access_denied:'Akses Ditolak',access_denied_help:'Anda tidak memiliki izin untuk mengakses catatan intelijen ini. Catatan mungkin berada di luar yurisdiksi Anda atau tidak tersedia pada tingkat akses saat ini.',intelligence_record:'Catatan intelijen',edit_record:'Edit catatan',
    correct_record:'Koreksi catatan · edit manusia',headline:'Judul',source_publisher:'Sumber / Penerbit',author:'Penulis',related_topics_label:'Topik Terkait',assigned_reviewer:'Peninjau yang Ditugaskan',original_preserved_help:'Teks sumber asli, bahasa, URL, dan berkas unggahan dipertahankan sebagaimana dikirim; lampirkan bukti tambahan alih-alih menggantinya.',english_translation:'Terjemahan Inggris',ai_unchanged_help:'Saran AI tetap tidak berubah. Catat koreksi manusia pada catatan analis.',analyst_notes:'Catatan Analis',save_corrections:'Simpan koreksi',
    original_source:'Sumber Asli',what_source_says:'ISI SUMBER',no_source_text:'Tidak ada teks sumber yang dimasukkan. Lihat URL asli atau materi terlampir.',view_full_source:'Lihat materi sumber lengkap · bukti dipertahankan',full_source_help:'Isi artikel di atas dapat dibersihkan untuk keterbacaan dan triage AI. Sumber lengkap dipertahankan di sini dan tidak pernah diganti secara diam-diam.',original_url:'URL Asli',open_original_source:'Buka sumber asli',author_account:'Penulis / Akun',platform_publisher:'Platform / Penerbit',published:'Diterbitkan',original_language:'Bahasa Asli',collected:'Dikumpulkan',translation:'Terjemahan',no_translation:'Belum ada terjemahan Inggris.',
    evidence_assessment:'Penilaian Bukti',evidence_type:'Jenis Bukti',verification_status:'Status Verifikasi',evidence_explain:'TERAMATI menjelaskan representasi sumber; BELUM DIVERIFIKASI berarti verifikasi sumber independen belum selesai. Validasi manusia tidak menetapkan pelanggaran.',mark_verified:'Tandai sumber DIVERIFIKASI MANUSIA',
    legacy_analysis:'Analisis Lama (jika tercatat)',ai_suggestion_not_finding:'SARAN AI · BUKAN TEMUAN',no_ai_analysis:'Belum ada analisis AI yang diterima.',review_ai_suggestions:'TINJAU SARAN AI',supporting_evidence:'Bukti Pendukung',no_files:'Tidak ada berkas terlampir.',attach_supporting_material:'Lampirkan materi pendukung asli (privat)',evidence_description:'Deskripsi bukti',upload_evidence:'Unggah bukti',
    related_intelligence:'Intelijen Terkait',entities:'Entitas',human_linked_watchlist:'Daftar Pantauan Tertaut oleh Manusia',watchlist_relationship_only:'Item Daftar Pantauan · Hanya hubungan entitas; tidak menyiratkan risiko, pelanggaran, atau prioritas.',view_watchlist_profile:'Lihat Profil Daftar Pantauan',human_review:'Tinjauan Manusia',decision:'Keputusan',timestamp:'Waktu',no_review_notes:'Belum ada catatan peninjauan.',validation_decision:'Keputusan Validasi',review_notes:'Catatan Peninjauan',geographic_pending_block:'Tinjauan ketidaksesuaian geografis masih menunggu. Validasi akhir diblokir sampai keputusan yurisdiksi diselesaikan.',triage_pending_block:'Selesaikan peninjauan semua saran Triage AI sebelum validasi akhir.',record_human_decision:'Catat keputusan manusia',restricted_reviewers:'Terbatas untuk peninjau berwenang.'
  }
};

const extendedTranslations={
  en:{
    actor_picture:'Actor Intelligence Picture',actor_picture_note:'Public, jurisdiction-scoped evidence only · relationships do not prove ownership.',loading_timeline:'Loading intelligence timeline...',registered_owned_channels:'Registered / owned channels',registered_account:'REGISTERED ACCOUNT',related_observed_publishers:'Related / observed publishers',related_observed_account:'RELATED / OBSERVED ACCOUNT · ownership not confirmed',activities:'Activities',locations:'Locations',narratives:'Narratives',associated_entities:'Associated entities',extracted_relationships:'Extracted relationships · not ownership',supervision_signals:'Supervision signals',not_yet_recorded:'Not yet recorded / approved',timeline:'Timeline',related_records:'related records',featured_appearances:'featured appearances in submitted public evidence',date_unknown:'Date unknown',registered_source_human_link:'Registered source / human link',activity:'Activity',narrative:'Narrative',signal:'Signal',not_human_approved:'Not human-approved',not_recorded:'Not recorded',not_determined:'Not determined',no_related_public_intelligence:'No related public intelligence in your jurisdiction.',
    intelligence_summary:'Intelligence Summary',final_summary_human_only:'FINAL SUMMARY · HUMAN-APPROVED ONLY',triage_fields_approved:'triage fields human-approved',human_approved_fields:'Human-approved analytical fields',what_happened:'What happened',who_involved:'Who is involved',where_signal:'Where / location signal',extracted_relationship_not_ownership:'Extracted relationship · not ownership',screening_confidence:'Screening confidence',why_attention:'Why attention may be warranted',check_next:'What to check next',screening_evidence_basis:'Screening evidence basis',evidence_gaps:'Evidence gaps',evidence_type_not_verification:'Evidence Type · not verification',recorded_source_context:'Recorded source & confirmed context',recorded_source_context_note:'These values come from source metadata or separate human confirmation. They are not AI-triage approvals.',confirmed_jurisdiction:'Confirmed jurisdiction',human_confirmed_relationship:'Human-confirmed monitored relationship',evidence_verification_status:'Evidence verification status',legacy_assessment:'LEGACY ASSESSMENT',historical_issue_category:'Historical potential issue category',historical_only_note:'Historical value only; not a current supervision signal or finding.',summary_footer:'Human-accepted or human-modified triage outcomes appear as approved values. Human-rejected fields are shown as rejected, genuinely undecided suggestions are shown as awaiting review, and fields never proposed by AI are shown separately. Original source evidence and AI proposals remain unchanged.',no_ai_suggestion:'No AI suggestion generated',rejected_by_reviewer:'Rejected by human reviewer',reason:'Reason',awaiting_human_review:'Awaiting human review',human_modified:'modified',human_accepted:'accepted',human_rejected:'rejected',authorized_reviewer:'authorized reviewer',human_approved_unavailable:'Human-approved value not available',not_human_confirmed:'Not human-confirmed',
    potential_duplicate:'Potential Duplicate',duplicate_explain:'Original records and evidence are retained separately. A human reviewer must decide whether to merge or keep them separate.',similarity:'Similarity',available_for_review:'Available for review',why_flagged:'Why flagged',view_comparison:'View Comparison',record:'Record',untitled:'Untitled',url:'URL',entity:'Entity',original_text:'Original text',no_text_entered:'No text entered',merge:'Merge',keep_separate:'Keep Separate',awaiting_authorized_reviewer:'Awaiting an authorized human reviewer.',preserved_source_records:'Preserved source records',no_url:'No URL',original_content_evidence:'Original content and evidence',
    source_recovery:'URL source recovery',retrieving:'Retrieving...',retrieve_source:'Retrieve source',source_retrieval_unavailable:'SOURCE RETRIEVAL UNAVAILABLE',recovered:'Recovered',recovery_note:'Automatic recovery only fills missing source fields. Existing original evidence is preserved and never silently replaced.',original_headline:'Original headline',author_account_lower:'Author / account',original_content_extract:'Original content / extract',save_missing_source_fields:'Save missing source fields',review_ai_below:'Review AI suggestions in the AI Triage section below',
    ai_triage_review_title:'AI Triage Review',ai_triage_only:'AI TRIAGE — SUGGESTIONS ONLY · NOT A FINDING',original_source_language:'Original source language',suggestions_pending_note:'Suggestions remain pending until an analyst decides on each one.',review_state:'Review state',suggestions_decided:'suggestions decided',legacy_unavailable:'Legacy suggestion details unavailable',ready_final_validation:'Ready for final human validation',generation:'Generation',cleaned_source_used:'Cleaned source used for AI triage',production_ai_triage:'Production AI triage',production_ai_unavailable:'Production AI unavailable — local fallback used',local_placeholder:'Local workflow placeholder',invalid_v3:'Invalid V3 proposal contract. Do not review these suggestions; contact an administrator.',no_ai_triage_saved:'No AI triage suggestions saved yet. The final summary and analysis remain human-approved only.',generate_ai_triage:'GENERATE AI TRIAGE',generating_suggestions:'Generating suggestions...',triage_source_understanding:'Source Understanding',triage_intelligence_extraction:'Intelligence Extraction',triage_supervision_screening:'Supervision Screening',triage_evidence_assessment:'Evidence Assessment',triage_source_facts:'Recorded source facts · read-only provenance, not AI conclusions',legacy_prescreening_note:'Legacy pre-screening suggestions remain pending and are not a current supervision signal or finding.',verification_unverified_note:'Verification status is UNVERIFIED until an authorized human independently verifies the source. This supervision signal does not establish a violation.',regenerate_suggestions:'Regenerate suggestions',boilerplate_removed:'boilerplate characters removed from the analysis copy. The recorded source evidence remains preserved.',production_ai_note:'generated through the configured OpenAI model. This remains a suggestion only and requires independent human Accept / Modify / Reject decisions.',fallback_note:'No automatic retry was attempted. Review carefully or regenerate later when the provider is available.',local_placeholder_note:'OpenAI is not configured for this deployment, so this is not production AI analysis.',undetermined:'Undetermined',of_word:'of',
    suggestion_summary:'What happened · factual summary',suggestion_translation:'English translation',suggestion_actors:'Actors · structured suggestions',suggestion_entity:'Actors / entities',suggestion_actor_evidence:'Actor evidence / excerpt',suggestion_content_type:'Content type · only if evidenced',suggestion_activity:'Observable activity',suggestion_location:'Location signal · not jurisdiction',suggestion_topics:'Topics · structured suggestions',suggestion_topic:'Topic',suggestion_narrative:'Narrative · intelligence context',suggestion_relationships:'Relationship to source · not ownership',suggestion_inference:'INFERENCE · not source fact',suggestion_inferences:'Inferences · not source facts',suggestion_supervision_signal:'Supervision signal · not a finding',suggestion_signal_reason:'Why this may warrant attention',suggestion_check_next:'What should be checked next',suggestion_priority:'Priority',suggestion_evidence_type:'Evidence type · not verification',suggestion_evidence_gaps:'Evidence gaps',suggestion_screening_basis:'Screening evidence basis',suggestion_screening_confidence:'Screening confidence',suggestion_issue_category:'Legacy potential issue category',suggestion_evidence_state:'Legacy evidence state',suggestion_analysis:'Legacy AI analysis',suggestion_reasoning:'Legacy reasoning',
    source_identity:'SOURCE IDENTITY',registered_account_match:'REGISTERED ACCOUNT MATCH',unresolved:'UNRESOLVED',observed_publisher:'Observed publisher',registered_entity:'Registered entity',registered_account_generic:'Registered account',match_basis:'Match basis',registered_account_url_comparison:'Registered account URL comparison',strict_match_note:'Strict registered-account checks confirmed source provenance, not post content or its claims.',url_match_note:'Registered URL match observed; registered-account ownership is not confirmed.',no_registered_match_note:'No confirmed registered-account match. This does not imply the account is fake, unofficial or unrelated.',related_entity_label:'Related entity',monitored_entity:'Monitored entity',other_requires_review:'OTHER / REQUIRES REVIEW',evidence_basis:'Evidence basis',publisher_not_ownership:'PUBLISHER does not establish registered-account ownership.',
    activity_timeline:'Activity Timeline',no_activity_recorded:'No activity recorded.',actor:'Actor',unknown:'Unknown',decision_label:'Decision',changed_from:'Changed from',final_value:'Final',hide_changes:'Hide changes',view_changes:'View changes',suggestion_type:'Suggestion type',ai_proposed:'AI Proposed',historical_excerpt:'historical excerpt',human_decision:'Human Decision',rejection_reason:'Rejection reason',ai_confidence:'AI confidence',human_final:'Human Final',timestamp_label:'Timestamp',reviewed_by:'Reviewer',recovered_label:'Recovered',
    jurisdiction:'Jurisdiction',confirmed_by:'Confirmed by',requires_jurisdiction:'Requires jurisdiction resolution · Not visible to regional users',submitter_proposed:'Submitter-proposed jurisdiction',confirm_jurisdiction:'Confirm Jurisdiction',change_confirmed_jurisdiction:'Change confirmed jurisdiction',
    geographic_mismatch_required:'GEOGRAPHIC MISMATCH — REVIEW REQUIRED',geographic_mismatch_reviewed:'Geographic mismatch — human reviewed',ai_source_jurisdiction:'AI/source-supported jurisdiction · NOT authoritative',supporting_location_evidence:'Supporting source-location evidence',no_location_recorded:'No location recorded',no_supporting_text:'No supporting text recorded.',final_validation_blocked:'Final validation is blocked until an authorized human resolves this mismatch. Source evidence cannot change the confirmed jurisdiction automatically.',human_reviewed:'Human reviewed',resulting_jurisdiction:'Resulting jurisdiction',review_reopened:'A previous geographic review exists, but the jurisdiction evidence changed. A new human decision is required.',analyst_reason_required:'An analyst note / reason is required.',analyst_note_reason:'Analyst note / reason *',keep_confirmed_jurisdiction:'KEEP CONFIRMED JURISDICTION',change_jurisdiction:'CHANGE JURISDICTION',confirm_changed_jurisdiction:'Confirm changed jurisdiction',
    publication_precision:'Publication date/time · source precision',publication_unknown:'Unknown date and time',publication_date_known:'Date known · time unknown',publication_exact:'Exact date and time',publication_date_label:'Publication date',publication_time_label:'Publication time',time_unknown_note:'Time UNKNOWN — no time will be recorded.',date_time_unknown_note:'UNKNOWN — no publication date or time will be recorded.',original_language_picker:'Original language',analyst_selection:'analyst selection',not_selected:'NOT SELECTED',selected:'Selected',search_languages:'Search languages to change',no_matching_language:'No matching language',detecting:'Detecting...',suggest_language:'Suggest language (optional)',system_suggested:'SYSTEM SUGGESTED',use_suggestion:'Use suggestion',
    jurisdiction_classification:'Jurisdiction classification',requires_regional_block:'Requires jurisdiction resolution. Regional users cannot access this record.',select_province:'Select province',optional:'optional',select_regency_city:'Select Regency / City',entire_province:'Entire province',remove_area:'Remove area',add_area:'Add area',ai_source_geography:'AI/source-supported geography — NOT an authoritative assignment',no_jurisdiction_identified:'Unresolved · No jurisdiction identified',resolution_confidence:'Resolution confidence',not_assessed:'Not assessed',normalized_kecamatan:'Normalized Kecamatan',extraction_confidence:'Extraction confidence (separate from resolution)',exact_source_evidence:'Exact source evidence',not_available:'Not available',extraction_provenance:'Extraction provenance',resolution_reference:'Resolution reference',
    awaiting_human_review_label:'Awaiting human review',no_issue_triage_note:'Based on the currently available source material, the AI did not identify an apparent election-supervision issue. This is a triage assessment, not a legal determination, and may be changed by an authorized analyst.',human_decision_label:'Human decision',change_decision:'Change decision',accept:'ACCEPT',modify:'MODIFY',reject:'REJECT',cancel_change:'Cancel change',reason_rejection:'Reason for rejection (required)',save_rejection:'Save rejection',save_modified_value:'Save modified value',possible_watchlist_match:'Possible Watchlist Match',human_accepted_linked:'Human Accepted & Linked',human_modified_linked:'Human Modified & Linked',match_strength:'Match strength',exact_name_match:'Exact-name match',name_overlap:'Name overlap',strength_high:'High',strength_moderate:'Moderate',analyst_linked_note:'Analyst-linked entity relationship; this is not a finding.',identity_unconfirmed_note:'Identity remains unconfirmed until human linking.',link_disclaimer:'A link is an entity relationship only and does not imply risk, priority, suspicion or a violation.',view_linked_profile:'View linked Watchlist profile',accept_link:'ACCEPT & LINK',choose_corrected_match:'Choose corrected watchlist match',choose_watchlist_entry:'Choose a watchlist entry',save_link_corrected:'Save & link corrected match',
    source_origin:'Source Origin',registered_owned_channel:'Registered Owned Channel',candidate:'Candidate',account:'Account',post:'Post',view_original_post:'View original post',confirmed_source_provenance:'CONFIRMED FROM REGISTERED SOURCE PROVENANCE',owned_channel_note:'This confirms the registered source relationship only—not the post content, its claims, personal authorship, or any election violation.',
    ai_triage_available:'AI TRIAGE AVAILABLE — AWAITING HUMAN REVIEW',linked_entry:'Linked entry',relationship_only_short:'Entity relationship only; no risk, violation or priority inferred.',no_description_short:'No description',uploaded_by:'uploaded by',approved_file_note:'Choose an approved file under 20 MB',record_changed_reload:'Record changed; reload before continuing',record_unavailable:'Record unavailable',not_classified_legacy:'Not classified (legacy)'
  },
  id:{
    actor_picture:'Gambaran Intelijen Aktor',actor_picture_note:'Hanya bukti publik dalam cakupan yurisdiksi · hubungan tidak membuktikan kepemilikan.',loading_timeline:'Memuat linimasa intelijen...',registered_owned_channels:'Kanal terdaftar / dimiliki',registered_account:'AKUN TERDAFTAR',related_observed_publishers:'Penerbit terkait / teramati',related_observed_account:'AKUN TERKAIT / TERAMATI · kepemilikan belum dikonfirmasi',activities:'Aktivitas',locations:'Lokasi',narratives:'Narasi',associated_entities:'Entitas terkait',extracted_relationships:'Hubungan yang diekstrak · bukan kepemilikan',supervision_signals:'Sinyal pengawasan',not_yet_recorded:'Belum tercatat / disetujui',timeline:'Linimasa',related_records:'catatan terkait',featured_appearances:'kemunculan utama dalam bukti publik yang dikirim',date_unknown:'Tanggal tidak diketahui',registered_source_human_link:'Sumber terdaftar / tautan manusia',activity:'Aktivitas',narrative:'Narasi',signal:'Sinyal',not_human_approved:'Belum disetujui manusia',not_recorded:'Belum tercatat',not_determined:'Belum ditentukan',no_related_public_intelligence:'Tidak ada intelijen publik terkait dalam yurisdiksi Anda.',
    intelligence_summary:'Ringkasan Intelijen',final_summary_human_only:'RINGKASAN AKHIR · HANYA YANG DISETUJUI MANUSIA',triage_fields_approved:'bidang triage disetujui manusia',human_approved_fields:'Bidang analitis yang disetujui manusia',what_happened:'Apa yang terjadi',who_involved:'Siapa yang terlibat',where_signal:'Di mana / sinyal lokasi',extracted_relationship_not_ownership:'Hubungan yang diekstrak · bukan kepemilikan',screening_confidence:'Kepercayaan penyaringan',why_attention:'Mengapa perlu perhatian',check_next:'Yang perlu diperiksa selanjutnya',screening_evidence_basis:'Dasar bukti penyaringan',evidence_gaps:'Kesenjangan bukti',evidence_type_not_verification:'Jenis Bukti · bukan verifikasi',recorded_source_context:'Sumber tercatat & konteks terkonfirmasi',recorded_source_context_note:'Nilai ini berasal dari metadata sumber atau konfirmasi manusia terpisah. Nilai ini bukan persetujuan triage AI.',confirmed_jurisdiction:'Yurisdiksi terkonfirmasi',human_confirmed_relationship:'Hubungan pemantauan yang dikonfirmasi manusia',evidence_verification_status:'Status verifikasi bukti',legacy_assessment:'PENILAIAN LAMA',historical_issue_category:'Kategori isu potensial historis',historical_only_note:'Hanya nilai historis; bukan sinyal pengawasan atau temuan saat ini.',summary_footer:'Hasil triage yang diterima atau diubah manusia tampil sebagai nilai yang disetujui. Bidang yang ditolak manusia ditampilkan sebagai ditolak, saran yang benar-benar belum diputuskan ditampilkan sebagai menunggu peninjauan, dan bidang yang tidak pernah diusulkan AI ditampilkan terpisah. Bukti sumber asli dan usulan AI tetap tidak berubah.',no_ai_suggestion:'Tidak ada saran AI yang dihasilkan',rejected_by_reviewer:'Ditolak oleh peninjau manusia',reason:'Alasan',awaiting_human_review:'Menunggu peninjauan manusia',human_modified:'diubah',human_accepted:'diterima',human_rejected:'ditolak',authorized_reviewer:'peninjau berwenang',human_approved_unavailable:'Nilai yang disetujui manusia tidak tersedia',not_human_confirmed:'Belum dikonfirmasi manusia',
    potential_duplicate:'Potensi Duplikat',duplicate_explain:'Catatan asli dan bukti dipertahankan secara terpisah. Peninjau manusia harus memutuskan apakah akan menggabungkan atau mempertahankannya terpisah.',similarity:'Kemiripan',available_for_review:'Tersedia untuk ditinjau',why_flagged:'Alasan ditandai',view_comparison:'Lihat Perbandingan',record:'Catatan',untitled:'Tanpa Judul',url:'URL',entity:'Entitas',original_text:'Teks asli',no_text_entered:'Tidak ada teks yang dimasukkan',merge:'Gabungkan',keep_separate:'Tetap Terpisah',awaiting_authorized_reviewer:'Menunggu peninjau manusia berwenang.',preserved_source_records:'Catatan sumber yang dipertahankan',no_url:'Tidak ada URL',original_content_evidence:'Konten asli dan bukti',
    source_recovery:'Pemulihan sumber URL',retrieving:'Mengambil...',retrieve_source:'Ambil sumber',source_retrieval_unavailable:'PEMULIHAN SUMBER TIDAK TERSEDIA',recovered:'Dipulihkan',recovery_note:'Pemulihan otomatis hanya mengisi bidang sumber yang kosong. Bukti asli tetap dipertahankan dan tidak pernah diganti secara diam-diam.',original_headline:'Judul asli',author_account_lower:'Penulis / akun',original_content_extract:'Konten / kutipan asli',save_missing_source_fields:'Simpan bidang sumber yang kosong',review_ai_below:'Tinjau saran AI di bagian Triage AI di bawah',
    ai_triage_review_title:'Tinjauan Triage AI',ai_triage_only:'TRIAGE AI — HANYA SARAN · BUKAN TEMUAN',original_source_language:'Bahasa sumber asli',suggestions_pending_note:'Saran tetap menunggu sampai analis memutuskan masing-masing saran.',review_state:'Status peninjauan',suggestions_decided:'saran telah diputuskan',legacy_unavailable:'Detail saran lama tidak tersedia',ready_final_validation:'Siap untuk validasi manusia akhir',generation:'Generasi',cleaned_source_used:'Sumber yang dibersihkan digunakan untuk triage AI',production_ai_triage:'Triage AI produksi',production_ai_unavailable:'AI produksi tidak tersedia — fallback lokal digunakan',local_placeholder:'Placeholder alur kerja lokal',invalid_v3:'Kontrak proposal V3 tidak valid. Jangan tinjau saran ini; hubungi administrator.',no_ai_triage_saved:'Belum ada saran triage AI tersimpan. Ringkasan akhir dan analisis tetap hanya yang disetujui manusia.',generate_ai_triage:'HASILKAN TRIAGE AI',generating_suggestions:'Menghasilkan saran...',triage_source_understanding:'Pemahaman Sumber',triage_intelligence_extraction:'Ekstraksi Intelijen',triage_supervision_screening:'Penyaringan Pengawasan',triage_evidence_assessment:'Penilaian Bukti',triage_source_facts:'Fakta sumber tercatat · asal baca-saja, bukan kesimpulan AI',legacy_prescreening_note:'Saran pra-penyaringan lama tetap menunggu dan bukan sinyal pengawasan atau temuan saat ini.',verification_unverified_note:'Status verifikasi tetap BELUM DIVERIFIKASI sampai manusia berwenang memverifikasi sumber secara independen. Sinyal pengawasan ini tidak menetapkan pelanggaran.',regenerate_suggestions:'Hasilkan ulang saran',boilerplate_removed:'karakter boilerplate dihapus dari salinan analisis. Bukti sumber yang tercatat tetap dipertahankan.',production_ai_note:'dihasilkan melalui model OpenAI yang dikonfigurasi. Ini tetap hanya saran dan memerlukan keputusan manusia Terima / Ubah / Tolak secara independen.',fallback_note:'Tidak ada percobaan ulang otomatis. Tinjau dengan cermat atau hasilkan ulang nanti saat penyedia tersedia.',local_placeholder_note:'OpenAI tidak dikonfigurasi untuk deployment ini, jadi ini bukan analisis AI produksi.',undetermined:'Belum ditentukan',of_word:'dari',
    suggestion_summary:'Apa yang terjadi · ringkasan faktual',suggestion_translation:'Terjemahan Inggris',suggestion_actors:'Aktor · saran terstruktur',suggestion_entity:'Aktor / entitas',suggestion_actor_evidence:'Bukti / kutipan aktor',suggestion_content_type:'Jenis konten · hanya jika didukung bukti',suggestion_activity:'Aktivitas teramati',suggestion_location:'Sinyal lokasi · bukan yurisdiksi',suggestion_topics:'Topik · saran terstruktur',suggestion_topic:'Topik',suggestion_narrative:'Narasi · konteks intelijen',suggestion_relationships:'Hubungan dengan sumber · bukan kepemilikan',suggestion_inference:'INFERENSI · bukan fakta sumber',suggestion_inferences:'Inferensi · bukan fakta sumber',suggestion_supervision_signal:'Sinyal pengawasan · bukan temuan',suggestion_signal_reason:'Mengapa ini mungkin perlu perhatian',suggestion_check_next:'Yang perlu diperiksa berikutnya',suggestion_priority:'Prioritas',suggestion_evidence_type:'Jenis bukti · bukan verifikasi',suggestion_evidence_gaps:'Kesenjangan bukti',suggestion_screening_basis:'Dasar bukti penyaringan',suggestion_screening_confidence:'Kepercayaan penyaringan',suggestion_issue_category:'Kategori isu potensial lama',suggestion_evidence_state:'Status bukti lama',suggestion_analysis:'Analisis AI lama',suggestion_reasoning:'Alasan AI lama',
    source_identity:'IDENTITAS SUMBER',registered_account_match:'KECOCOKAN AKUN TERDAFTAR',unresolved:'BELUM TERSELESAIKAN',observed_publisher:'Penerbit teramati',registered_entity:'Entitas terdaftar',registered_account_generic:'Akun terdaftar',match_basis:'Dasar kecocokan',registered_account_url_comparison:'Perbandingan URL akun terdaftar',strict_match_note:'Pemeriksaan ketat akun terdaftar mengonfirmasi asal sumber, bukan isi posting atau klaimnya.',url_match_note:'Kecocokan URL terdaftar teramati; kepemilikan akun terdaftar belum dikonfirmasi.',no_registered_match_note:'Tidak ada kecocokan akun terdaftar yang terkonfirmasi. Ini tidak berarti akun tersebut palsu, tidak resmi, atau tidak terkait.',related_entity_label:'Entitas terkait',monitored_entity:'Entitas dipantau',other_requires_review:'LAINNYA / PERLU TINJAUAN',evidence_basis:'Dasar bukti',publisher_not_ownership:'PENERBIT tidak menetapkan kepemilikan akun terdaftar.',
    activity_timeline:'Linimasa Aktivitas',no_activity_recorded:'Belum ada aktivitas tercatat.',actor:'Aktor',unknown:'Tidak diketahui',decision_label:'Keputusan',changed_from:'Diubah dari',final_value:'Akhir',hide_changes:'Sembunyikan perubahan',view_changes:'Lihat perubahan',suggestion_type:'Jenis saran',ai_proposed:'Usulan AI',historical_excerpt:'kutipan historis',human_decision:'Keputusan Manusia',rejection_reason:'Alasan penolakan',ai_confidence:'Kepercayaan AI',human_final:'Hasil Akhir Manusia',timestamp_label:'Waktu',reviewed_by:'Peninjau',recovered_label:'Dipulihkan',
    jurisdiction:'Yurisdiksi',confirmed_by:'Dikonfirmasi oleh',requires_jurisdiction:'Memerlukan penyelesaian yurisdiksi · Tidak terlihat bagi pengguna regional',submitter_proposed:'Yurisdiksi yang diusulkan pengirim',confirm_jurisdiction:'Konfirmasi Yurisdiksi',change_confirmed_jurisdiction:'Ubah yurisdiksi terkonfirmasi',
    geographic_mismatch_required:'KETIDAKSESUAIAN GEOGRAFIS — PERLU TINJAUAN',geographic_mismatch_reviewed:'Ketidaksesuaian geografis — telah ditinjau manusia',ai_source_jurisdiction:'Yurisdiksi yang didukung AI/sumber · TIDAK berwenang',supporting_location_evidence:'Bukti lokasi pendukung dari sumber',no_location_recorded:'Tidak ada lokasi tercatat',no_supporting_text:'Tidak ada teks pendukung tercatat.',final_validation_blocked:'Validasi akhir diblokir sampai ketidaksesuaian ini diselesaikan oleh manusia berwenang. Bukti sumber tidak dapat mengubah yurisdiksi terkonfirmasi secara otomatis.',human_reviewed:'Ditinjau manusia',resulting_jurisdiction:'Yurisdiksi hasil',review_reopened:'Tinjauan geografis sebelumnya ada, tetapi bukti yurisdiksi berubah. Keputusan manusia baru diperlukan.',analyst_reason_required:'Catatan / alasan analis wajib diisi.',analyst_note_reason:'Catatan / alasan analis *',keep_confirmed_jurisdiction:'PERTAHANKAN YURISDIKSI TERKONFIRMASI',change_jurisdiction:'UBAH YURISDIKSI',confirm_changed_jurisdiction:'Konfirmasi perubahan yurisdiksi',
    publication_precision:'Tanggal/waktu publikasi · ketelitian sumber',publication_unknown:'Tanggal dan waktu tidak diketahui',publication_date_known:'Tanggal diketahui · waktu tidak diketahui',publication_exact:'Tanggal dan waktu tepat',publication_date_label:'Tanggal publikasi',publication_time_label:'Waktu publikasi',time_unknown_note:'Waktu TIDAK DIKETAHUI — tidak ada waktu yang dicatat.',date_time_unknown_note:'TIDAK DIKETAHUI — tidak ada tanggal atau waktu publikasi yang dicatat.',original_language_picker:'Bahasa asli',analyst_selection:'pilihan analis',not_selected:'BELUM DIPILIH',selected:'Dipilih',search_languages:'Cari bahasa untuk mengubah',no_matching_language:'Tidak ada bahasa yang cocok',detecting:'Mendeteksi...',suggest_language:'Sarankan bahasa (opsional)',system_suggested:'SARAN SISTEM',use_suggestion:'Gunakan saran',
    jurisdiction_classification:'Klasifikasi yurisdiksi',requires_regional_block:'Memerlukan penyelesaian yurisdiksi. Pengguna regional tidak dapat mengakses catatan ini.',select_province:'Pilih provinsi',optional:'opsional',select_regency_city:'Pilih Kabupaten / Kota',entire_province:'Seluruh provinsi',remove_area:'Hapus wilayah',add_area:'Tambah wilayah',ai_source_geography:'Geografi yang didukung AI/sumber — BUKAN penetapan berwenang',no_jurisdiction_identified:'Belum terselesaikan · Tidak ada yurisdiksi teridentifikasi',resolution_confidence:'Kepercayaan resolusi',not_assessed:'Belum dinilai',normalized_kecamatan:'Kecamatan ternormalisasi',extraction_confidence:'Kepercayaan ekstraksi (terpisah dari resolusi)',exact_source_evidence:'Bukti sumber yang tepat',not_available:'Tidak tersedia',extraction_provenance:'Asal ekstraksi',resolution_reference:'Referensi resolusi',
    awaiting_human_review_label:'Menunggu peninjauan manusia',no_issue_triage_note:'Berdasarkan materi sumber yang tersedia saat ini, AI tidak mengidentifikasi isu pengawasan pemilu yang tampak. Ini adalah penilaian triage, bukan penetapan hukum, dan dapat diubah oleh analis berwenang.',human_decision_label:'Keputusan manusia',change_decision:'Ubah keputusan',accept:'TERIMA',modify:'UBAH',reject:'TOLAK',cancel_change:'Batalkan perubahan',reason_rejection:'Alasan penolakan (wajib)',save_rejection:'Simpan penolakan',save_modified_value:'Simpan nilai yang diubah',possible_watchlist_match:'Kemungkinan Kecocokan Daftar Pantauan',human_accepted_linked:'Diterima Manusia & Ditautkan',human_modified_linked:'Diubah Manusia & Ditautkan',match_strength:'Kekuatan kecocokan',exact_name_match:'Kecocokan nama persis',name_overlap:'Kemiripan nama',strength_high:'Tinggi',strength_moderate:'Sedang',analyst_linked_note:'Hubungan entitas yang ditautkan analis; ini bukan temuan.',identity_unconfirmed_note:'Identitas tetap belum dikonfirmasi sampai penautan manusia.',link_disclaimer:'Tautan hanya menunjukkan hubungan entitas dan tidak menyiratkan risiko, prioritas, kecurigaan, atau pelanggaran.',view_linked_profile:'Lihat profil Daftar Pantauan tertaut',accept_link:'TERIMA & TAUTKAN',choose_corrected_match:'Pilih kecocokan Daftar Pantauan yang dikoreksi',choose_watchlist_entry:'Pilih entri Daftar Pantauan',save_link_corrected:'Simpan & tautkan kecocokan terkoreksi',
    source_origin:'Asal Sumber',registered_owned_channel:'Kanal Milik Terdaftar',candidate:'Kandidat',account:'Akun',post:'Posting',view_original_post:'Lihat posting asli',confirmed_source_provenance:'DIKONFIRMASI DARI ASAL SUMBER TERDAFTAR',owned_channel_note:'Ini hanya mengonfirmasi hubungan sumber terdaftar—bukan isi posting, klaimnya, penulis pribadi, atau pelanggaran pemilu apa pun.',
    ai_triage_available:'TRIAGE AI TERSEDIA — MENUNGGU PENINJAUAN MANUSIA',linked_entry:'Entri tertaut',relationship_only_short:'Hanya hubungan entitas; tidak menyiratkan risiko, pelanggaran, atau prioritas.',no_description_short:'Tanpa deskripsi',uploaded_by:'diunggah oleh',approved_file_note:'Pilih berkas yang disetujui berukuran di bawah 20 MB',record_changed_reload:'Catatan berubah; muat ulang sebelum melanjutkan',record_unavailable:'Catatan tidak tersedia',not_classified_legacy:'Belum diklasifikasikan (lama)'
  }
};

const valueLabels={
  id:{
    'Critical':'Kritis','High':'Tinggi','Medium':'Sedang','Low':'Rendah',
    'Active':'Aktif','Inactive':'Tidak Aktif','Under Review':'Dalam Peninjauan',
    'Pending Review':'Menunggu Peninjauan','Awaiting Validation':'Menunggu Validasi',
    'Validated as Relevant Intelligence':'Divalidasi sebagai Intelijen Relevan',
    'Request More Information':'Minta Informasi Tambahan','Not Relevant':'Tidak Relevan',
    'Escalate for Further Review':'Eskalasi untuk Peninjauan Lanjutan',
    'UNVERIFIED':'BELUM DIVERIFIKASI','HUMAN_VERIFIED':'DIVERIFIKASI MANUSIA','VERIFIED':'DIVERIFIKASI',
    'OBSERVED':'TERAMATI','INFERRED':'INFERENSI',
    'NO SIGNAL IDENTIFIED':'TIDAK ADA SINYAL TERIDENTIFIKASI',
    'MONITOR':'PANTAU','REVIEW RECOMMENDED':'PENINJAUAN DIREKOMENDASIKAN',
    'POTENTIAL REGULATORY ISSUE':'POTENSI ISU REGULASI',
    'DISCOVERED':'DITEMUKAN','RELEVANT':'RELEVAN','NOT_RELEVANT':'TIDAK RELEVAN',
    'PROMOTED':'DITAMBAHKAN KE INTELIJEN','Human Accepted':'Diterima Manusia','Human Modified':'Diubah Manusia','Human Rejected':'Ditolak Manusia','REVIEW COMPLETE':'PENINJAUAN SELESAI','REVIEW PENDING':'PENINJAUAN MENUNGGU','NOT GENERATED':'BELUM DIHASILKAN',
    'Candidate':'Kandidat','Political Party':'Partai Politik','Campaign Team':'Tim Kampanye','Official Account':'Akun Resmi',
    'Election-related Public Figure':'Tokoh Publik Terkait Pemilu','Media':'Media','Public Community':'Komunitas Publik','Organisation':'Organisasi',
    'Topic / Issue':'Topik / Isu','Location':'Lokasi','Other Approved Public Source':'Sumber Publik Lain yang Disetujui',
    'Associated with':'Terkait dengan','Member of':'Anggota dari','Campaign relationship':'Hubungan kampanye',
    'Publicly linked to':'Terkait secara publik dengan','Other observed relationship':'Hubungan lain yang teramati'
  }
};

export function LanguageProvider({children}){
  const [language,setLanguageState]=useState(()=>localStorage.getItem('bawaslu-language')||'en');
  const setLanguage=next=>setLanguageState(next==='id'?'id':'en');
  useEffect(()=>{
    localStorage.setItem('bawaslu-language',language);
    document.documentElement.lang=language==='id'?'id':'en';
  },[language]);
  const api=useMemo(()=>({
    language,
    setLanguage,
    t:key=>translations[language]?.[key]??extendedTranslations[language]?.[key]??translations.en[key]??extendedTranslations.en[key]??key,
    label:value=>valueLabels[language]?.[value]??value
  }),[language]);
  return <LanguageContext.Provider value={api}>{children}</LanguageContext.Provider>;
}

export function useLanguage(){
  const ctx=useContext(LanguageContext);
  if(!ctx)throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
