import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext=createContext(null);

const translations={
  en:{
    workspace:'Workspace',future_modules:'Future modules',soon:'SOON',
    home:'Home',watchlist:'Watchlist',social_listening:'Social Listening',intelligence_inbox:'Intelligence Inbox',
    intelligence_assistant:'BAWASLU Intelligence Assistant',add_intelligence:'Add Intelligence',data_sources:'Data Sources',
    validation:'Validation',administration:'Administration',intelligence_command:'Intelligence Command',
    secure_workspace:'Secure workspace',authorized_user:'Authorized user',
    election_supervision_intelligence:'Election supervision / Intelligence',add:'Add',
    loading_access:'Loading BAWASLU access...',inactive_access:'Your BAWASLU access is inactive.',select:'Select',

    workspace_overview:'Workspace Overview',
    intelligence_situation:'Intelligence Situation',
    home_intro:'Operational overview of the existing BAWASLU workspace and the items that need attention now.',
    operational_metrics:'Operational metrics',
    authorized_scope_note:'Counts are limited to intelligence records available within your authorized scope.',
    open:'Open',
    pending_intelligence_review:'Pending Intelligence Review',
    pending_intelligence_detail:'Needs human review or validation.',
    validated_intelligence:'Validated Intelligence',
    validated_intelligence_detail:'Human-validated relevant intelligence.',
    unverified_evidence:'UNVERIFIED Evidence',
    unverified_evidence_detail:'Source verification is still pending.',
    jurisdiction_unresolved:'Jurisdiction Unresolved',
    jurisdiction_unresolved_detail:'Needs human jurisdiction confirmation.',
    ai_triage_awaiting_review:'AI Triage Awaiting Review',
    ai_triage_detail:'Generated suggestions still need analyst decisions.',
    social_review_queue:'Social Review Queue',
    social_review_detail:'Stored results awaiting human disposition.',
    attention_now:'What needs attention now',
    attention_rank_note:'Ranked by geographic mismatch, AI review, human review, jurisdiction and priority.',
    open_inbox:'Open inbox',
    geographic_mismatch:'Geographic mismatch',
    ai_triage_review:'AI triage review',
    pending_human_review:'Pending human review',
    critical_priority:'Critical priority',
    high_priority:'High priority',
    jurisdiction_not_confirmed:'Jurisdiction not confirmed',
    validated_monitoring:'Validated intelligence & monitoring queues',
    validated_monitoring_note:'Compact management view of validated intelligence, Watchlist state and stored Social Listening review work.',
    latest_validated:'Latest validated intelligence',
    view_all:'View all',
    watchlist_summary_unavailable:'Watchlist summary unavailable. The rest of Home remains available.',
    loading_watchlist_summary:'Loading Watchlist summary...',
    social_queue_unavailable:'Social Listening queue status is temporarily unavailable.',
    no_socialcrawl_search:'No SocialCrawl search was triggered.',
    loading_social_queue:'Loading stored Social Listening queue...',
    active:'Active',under_review:'Under Review',inactive:'Inactive',
    discovered:'Discovered',relevant:'Relevant',monitor:'Monitor',
    validated_label:'Validated',source_label:'Source',verification_label:'Verification',
    recent_activity:'Recent activity',
    recent_activity_note:'Latest recorded workspace actions. Activity failure does not block the operational dashboard.',
    recent_activity_unavailable:'Recent activity is temporarily unavailable.',
    no_recent_activity:'No recent activity yet.',
    system:'System',
    no_immediate_attention:'No intelligence currently requires immediate attention.',
    no_validated_scope:'No validated intelligence in your authorized scope yet.',
    untitled_intelligence:'Untitled intelligence',
    source_not_recorded:'Source not recorded',
    confirmed:'Confirmed',national:'National',

    collection_triage:'Collection / Triage',
    all_intelligence:'All intelligence',
    pending_review:'Pending Review',
    validated:'Validated',
    unverified:'UNVERIFIED',
    ai_triage_waiting:'AI Triage Awaiting Review',
    search_placeholder:'Search keywords, ID, entity or location...',
    all_prefix:'All',
    sort_recently_updated:'Recently updated',
    sort_newest_created:'Newest created',
    sort_oldest_created:'Oldest created',
    sort_highest_priority:'Highest priority',
    sort_intelligence_id:'Intelligence ID',
    view:'View',
    clear_all_filters:'Clear all filters',
    loading_intelligence:'Loading intelligence...',
    submitted_jurisdiction:'Submitted for national jurisdiction resolution. Regional users cannot access the record until it is confirmed.',
    match:'match',matches:'matches',
    records_authorized_scope:'records in authorized scope',
    record_authorized_scope:'record in authorized scope',
    filter_search:'Search',filter_date:'Date',filter_entity:'Entity',filter_verification:'Verification',
    filter_review_status:'Review status',filter_priority:'Priority',filter_province:'Province',
    filter_regency_city:'Regency / City',filter_platform:'Platform',filter_evidence_type:'Evidence type',
    filter_reviewer:'Reviewer',filter_source_type:'Source type',filter_supervision_signal:'Supervision signal',
    location:'Location',evidence:'Evidence',priority:'Priority',reviewer:'Reviewer',updated:'Updated',
    unassigned:'Unassigned',no_related_entity:'No related entity',
    source_type_not_recorded:'Source type not recorded',
    jurisdiction_unresolved_short:'Jurisdiction unresolved',
    geographic_review_required:'Geographic mismatch review required',
    no_match_current_filters:'No intelligence matches the current view and filters.',
    not_classified:'Not classified'
    ,result:'result',results:'results',
    monitoring_registry:'Monitoring registry',watchlist_intro:'Human-managed entities, issues, locations, relationships and public source accounts used across the workspace.',
    add_watchlist_item:'Add Watchlist Item',editing_watchlist_item:'Editing existing watchlist item',create_watchlist_item:'Create watchlist item',edit_prefix:'Edit',watchlist_item:'Watchlist item',new_watchlist_item:'New watchlist item',edit_watchlist_help:'Save changes to update this existing record. Cancel returns to the watchlist without changing it.',
    name:'Name',type:'Type',monitoring_priority:'Monitoring Priority',province:'Province',regency_city:'Regency / City',related_election:'Related Election',related_entity:'Related Entity',related_topics:'Related Topics (comma-separated)',monitoring_status:'Monitoring Status',description:'Description',notes:'Notes',
    saving:'Saving...',save_changes:'Save changes',create_item:'Create item',cancel:'Cancel',search_watchlist:'Search name, type, topic or geography...',all_statuses:'All statuses',all_types:'All types',all_priorities:'All priorities',all_geographies:'All geographies',loading_watchlist:'Loading watchlist...',
    no_description:'No description provided.',nationwide:'Nationwide',election_not_specified:'Election not specified',created:'Created',view_related_intelligence:'View related intelligence',edit:'Edit',activate:'Activate',set_under_review:'Set Under Review',deactivate:'Deactivate',
    public_accounts_urls:'PUBLIC ACCOUNTS & URLS',no_public_account:'No registered public account / URL.',public_url:'Public URL',handle:'Handle',save_account:'Save account',add_account:'Add account',add_public_account:'+ Add public URL / account',
    related_watchlist_items:'RELATED WATCHLIST ITEMS',no_recorded_relationship:'No recorded relationship.',select_watchlist_item:'Select watchlist item',select_relationship_type:'Select relationship type',link_items:'Link items',link_watchlist_item:'+ Link watchlist item',remove_public_confirm:'Remove this public account / URL from the watchlist?',remove_relationship_confirm:'Remove this relationship?',no_watchlist_filter_match:'No watchlist items match the current filters.',
    watchlist_profile_loading:'Loading Watchlist profile...',watchlist_profile_unavailable:'Watchlist profile unavailable in your jurisdiction.',watchlist_profile_label:'Watchlist profile · Entity relationship only',topics:'Topics',public_accounts:'Public accounts & URLs',registry_relationships:'Registry relationships',none_recorded:'None recorded.',watchlist_entry:'Watchlist entry',watchlist_disclaimer:'A Watchlist link identifies an entity relationship only. It does not establish identity, risk, suspicion, a violation, priority, scoring, or enforcement grounds.',
    back_inbox:'Intelligence Inbox',record_display_error:'Record display error',record_display_error_help:'This intelligence record could not be displayed safely. The record remains stored; return to the inbox and try again after refresh.',unexpected_display_error:'Unexpected display error',return_inbox:'Return to Intelligence Inbox',refresh_record:'Refresh record',loading_record:'Loading intelligence record...',access_denied:'Access Denied',access_denied_help:'You do not have permission to access this intelligence record. The record may be outside your assigned jurisdiction or unavailable under your current access level.',intelligence_record:'Intelligence record',edit_record:'Edit record',
    correct_record:'Correct record · human edit',headline:'Headline',source_publisher:'Source / Publisher',author:'Author',related_topics_label:'Related Topics',assigned_reviewer:'Assigned Reviewer',original_preserved_help:'Original source text, language, URL and uploaded files are preserved as submitted; attach additional evidence rather than replacing them.',english_translation:'English Translation',ai_unchanged_help:'AI suggestions remain unchanged. Record human corrections in analyst notes.',analyst_notes:'Analyst Notes',save_corrections:'Save corrections',
    original_source:'Original Source',what_source_says:'WHAT THE SOURCE SAYS',no_source_text:'No source text entered. Consult the original URL or attached material.',view_full_source:'View full retrieved source material · preserved evidence',full_source_help:'The article body above may be cleaned for readability and AI triage. The full retrieved source is preserved here and is never silently replaced.',original_url:'Original URL',open_original_source:'Open original source',author_account:'Author / Account',platform_publisher:'Platform / Publisher',published:'Published',original_language:'Original Language',collected:'Collected',translation:'Translation',no_translation:'No English translation recorded.',
    evidence_assessment:'Evidence Assessment',evidence_type:'Evidence Type',verification_status:'Verification Status',evidence_explain:'OBSERVED describes what the source represents; UNVERIFIED means independent source verification has not been completed. Human validation does not establish a violation.',mark_verified:'Mark source HUMAN VERIFIED',
    legacy_analysis:'Legacy Analysis (if recorded)',ai_suggestion_not_finding:'AI SUGGESTION · NOT A FINDING',no_ai_analysis:'No AI analysis accepted.',review_ai_suggestions:'REVIEW AI SUGGESTIONS',supporting_evidence:'Supporting Evidence',no_files:'No files attached.',attach_supporting_material:'Attach original supporting material (private)',evidence_description:'Evidence description',upload_evidence:'Upload evidence',
    related_intelligence:'Related Intelligence',entities:'Entities',human_linked_watchlist:'Human-linked Watchlist',watchlist_relationship_only:'Watchlist entry · Entity relationship only; no risk, violation or priority inferred.',view_watchlist_profile:'View Watchlist Profile',human_review:'Human Review',decision:'Decision',timestamp:'Timestamp',no_review_notes:'No review notes yet.',validation_decision:'Validation Decision',review_notes:'Review Notes',geographic_pending_block:'Geographic mismatch review is pending. Final validation is blocked until the jurisdiction decision above is completed.',triage_pending_block:'Complete review of all generated AI Triage suggestions before final validation.',record_human_decision:'Record human decision',restricted_reviewers:'Restricted to authorized reviewers.'
  },

  id:{
    workspace:'Ruang Kerja',future_modules:'Modul Mendatang',soon:'SEGERA',
    home:'Beranda',watchlist:'Daftar Pantauan',social_listening:'Pemantauan Media Sosial',intelligence_inbox:'Kotak Masuk Intelijen',
    intelligence_assistant:'Asisten Intelijen BAWASLU',add_intelligence:'Tambah Intelijen',data_sources:'Sumber Data',
    validation:'Validasi',administration:'Administrasi',intelligence_command:'Komando Intelijen',
    secure_workspace:'Ruang kerja aman',authorized_user:'Pengguna berwenang',
    election_supervision_intelligence:'Pengawasan Pemilu / Intelijen',add:'Tambah',
    loading_access:'Memuat akses BAWASLU...',inactive_access:'Akses BAWASLU Anda tidak aktif.',select:'Pilih',

    workspace_overview:'Ikhtisar Ruang Kerja',
    intelligence_situation:'Situasi Intelijen',
    home_intro:'Ikhtisar operasional ruang kerja BAWASLU dan hal-hal yang memerlukan perhatian saat ini.',
    operational_metrics:'Metrik Operasional',
    authorized_scope_note:'Jumlah dibatasi pada catatan intelijen yang tersedia dalam cakupan akses Anda.',
    open:'Buka',
    pending_intelligence_review:'Intelijen Menunggu Peninjauan',
    pending_intelligence_detail:'Memerlukan peninjauan atau validasi manusia.',
    validated_intelligence:'Intelijen Tervalidasi',
    validated_intelligence_detail:'Intelijen relevan yang telah divalidasi manusia.',
    unverified_evidence:'Bukti BELUM DIVERIFIKASI',
    unverified_evidence_detail:'Verifikasi sumber masih menunggu.',
    jurisdiction_unresolved:'Yurisdiksi Belum Ditentukan',
    jurisdiction_unresolved_detail:'Memerlukan konfirmasi yurisdiksi oleh manusia.',
    ai_triage_awaiting_review:'Triage AI Menunggu Peninjauan',
    ai_triage_detail:'Saran yang dihasilkan masih memerlukan keputusan analis.',
    social_review_queue:'Antrean Tinjauan Sosial',
    social_review_detail:'Hasil tersimpan menunggu keputusan manusia.',
    attention_now:'Yang Perlu Diperhatikan Sekarang',
    attention_rank_note:'Diurutkan berdasarkan ketidaksesuaian geografis, tinjauan AI, tinjauan manusia, yurisdiksi, dan prioritas.',
    open_inbox:'Buka Kotak Masuk',
    geographic_mismatch:'Ketidaksesuaian geografis',
    ai_triage_review:'Tinjauan triage AI',
    pending_human_review:'Menunggu tinjauan manusia',
    critical_priority:'Prioritas kritis',
    high_priority:'Prioritas tinggi',
    jurisdiction_not_confirmed:'Yurisdiksi belum dikonfirmasi',
    validated_monitoring:'Intelijen Tervalidasi & Antrean Pemantauan',
    validated_monitoring_note:'Tampilan ringkas untuk intelijen tervalidasi, status Daftar Pantauan, dan pekerjaan tinjauan Pemantauan Media Sosial yang tersimpan.',
    latest_validated:'Intelijen Tervalidasi Terbaru',
    view_all:'Lihat Semua',
    watchlist_summary_unavailable:'Ringkasan Daftar Pantauan sementara tidak tersedia. Bagian Beranda lainnya tetap tersedia.',
    loading_watchlist_summary:'Memuat ringkasan Daftar Pantauan...',
    social_queue_unavailable:'Status antrean Pemantauan Media Sosial sementara tidak tersedia.',
    no_socialcrawl_search:'Tidak ada pencarian SocialCrawl yang dijalankan.',
    loading_social_queue:'Memuat antrean Pemantauan Media Sosial yang tersimpan...',
    active:'Aktif',under_review:'Dalam Peninjauan',inactive:'Tidak Aktif',
    discovered:'Ditemukan',relevant:'Relevan',monitor:'Pantau',
    validated_label:'Divalidasi',source_label:'Sumber',verification_label:'Verifikasi',
    recent_activity:'Aktivitas Terbaru',
    recent_activity_note:'Tindakan terbaru yang tercatat di ruang kerja. Kegagalan aktivitas tidak memblokir dasbor operasional.',
    recent_activity_unavailable:'Aktivitas terbaru sementara tidak tersedia.',
    no_recent_activity:'Belum ada aktivitas terbaru.',
    system:'Sistem',
    no_immediate_attention:'Tidak ada intelijen yang saat ini memerlukan perhatian segera.',
    no_validated_scope:'Belum ada intelijen tervalidasi dalam cakupan akses Anda.',
    untitled_intelligence:'Intelijen Tanpa Judul',
    source_not_recorded:'Sumber belum tercatat',
    confirmed:'Dikonfirmasi',national:'Nasional',

    collection_triage:'Pengumpulan / Triage',
    all_intelligence:'Semua Intelijen',
    pending_review:'Menunggu Peninjauan',
    validated:'Tervalidasi',
    unverified:'BELUM DIVERIFIKASI',
    ai_triage_waiting:'Triage AI Menunggu Peninjauan',
    search_placeholder:'Cari kata kunci, ID, entitas, atau lokasi...',
    all_prefix:'Semua',
    sort_recently_updated:'Terakhir Diperbarui',
    sort_newest_created:'Terbaru Dibuat',
    sort_oldest_created:'Terlama Dibuat',
    sort_highest_priority:'Prioritas Tertinggi',
    sort_intelligence_id:'ID Intelijen',
    view:'Tampilan',
    clear_all_filters:'Hapus Semua Filter',
    loading_intelligence:'Memuat intelijen...',
    submitted_jurisdiction:'Diajukan untuk penyelesaian yurisdiksi nasional. Pengguna regional tidak dapat mengakses catatan hingga dikonfirmasi.',
    match:'cocok',matches:'cocok',
    records_authorized_scope:'catatan dalam cakupan akses',
    record_authorized_scope:'catatan dalam cakupan akses',
    filter_search:'Pencarian',filter_date:'Tanggal',filter_entity:'Entitas',filter_verification:'Verifikasi',
    filter_review_status:'Status Peninjauan',filter_priority:'Prioritas',filter_province:'Provinsi',
    filter_regency_city:'Kabupaten / Kota',filter_platform:'Platform',filter_evidence_type:'Jenis Bukti',
    filter_reviewer:'Peninjau',filter_source_type:'Jenis Sumber',filter_supervision_signal:'Sinyal Pengawasan',
    location:'Lokasi',evidence:'Bukti',priority:'Prioritas',reviewer:'Peninjau',updated:'Diperbarui',
    unassigned:'Belum Ditugaskan',no_related_entity:'Tidak ada entitas terkait',
    source_type_not_recorded:'Jenis sumber belum tercatat',
    jurisdiction_unresolved_short:'Yurisdiksi belum ditentukan',
    geographic_review_required:'Tinjauan ketidaksesuaian geografis diperlukan',
    no_match_current_filters:'Tidak ada intelijen yang cocok dengan tampilan dan filter saat ini.',
    not_classified:'Belum Diklasifikasikan'
    ,result:'hasil',results:'hasil',
    monitoring_registry:'Registri Pemantauan',watchlist_intro:'Entitas, isu, lokasi, hubungan, dan akun sumber publik yang dikelola manusia dan digunakan di seluruh ruang kerja.',
    add_watchlist_item:'Tambah Item Pantauan',editing_watchlist_item:'Mengedit item pantauan',create_watchlist_item:'Buat item pantauan',edit_prefix:'Edit',watchlist_item:'Item pantauan',new_watchlist_item:'Item pantauan baru',edit_watchlist_help:'Simpan perubahan untuk memperbarui catatan ini. Batal akan kembali ke daftar pantauan tanpa mengubahnya.',
    name:'Nama',type:'Jenis',monitoring_priority:'Prioritas Pemantauan',province:'Provinsi',regency_city:'Kabupaten / Kota',related_election:'Pemilu Terkait',related_entity:'Entitas Terkait',related_topics:'Topik Terkait (dipisahkan koma)',monitoring_status:'Status Pemantauan',description:'Deskripsi',notes:'Catatan',
    saving:'Menyimpan...',save_changes:'Simpan perubahan',create_item:'Buat item',cancel:'Batal',search_watchlist:'Cari nama, jenis, topik, atau wilayah...',all_statuses:'Semua status',all_types:'Semua jenis',all_priorities:'Semua prioritas',all_geographies:'Semua wilayah',loading_watchlist:'Memuat daftar pantauan...',
    no_description:'Tidak ada deskripsi.',nationwide:'Nasional',election_not_specified:'Pemilu belum ditentukan',created:'Dibuat',view_related_intelligence:'Lihat intelijen terkait',edit:'Edit',activate:'Aktifkan',set_under_review:'Tandai Dalam Peninjauan',deactivate:'Nonaktifkan',
    public_accounts_urls:'AKUN PUBLIK & URL',no_public_account:'Belum ada akun publik / URL terdaftar.',public_url:'URL Publik',handle:'Handle',save_account:'Simpan akun',add_account:'Tambah akun',add_public_account:'+ Tambah URL / akun publik',
    related_watchlist_items:'ITEM DAFTAR PANTAUAN TERKAIT',no_recorded_relationship:'Belum ada hubungan tercatat.',select_watchlist_item:'Pilih item daftar pantauan',select_relationship_type:'Pilih jenis hubungan',link_items:'Hubungkan item',link_watchlist_item:'+ Hubungkan item daftar pantauan',remove_public_confirm:'Hapus akun publik / URL ini dari daftar pantauan?',remove_relationship_confirm:'Hapus hubungan ini?',no_watchlist_filter_match:'Tidak ada item daftar pantauan yang cocok dengan filter saat ini.',
    watchlist_profile_loading:'Memuat profil Daftar Pantauan...',watchlist_profile_unavailable:'Profil Daftar Pantauan tidak tersedia dalam yurisdiksi Anda.',watchlist_profile_label:'Profil Daftar Pantauan · Hanya hubungan entitas',topics:'Topik',public_accounts:'Akun Publik & URL',registry_relationships:'Hubungan Registri',none_recorded:'Belum ada.',watchlist_entry:'Item Daftar Pantauan',watchlist_disclaimer:'Tautan Daftar Pantauan hanya menunjukkan hubungan entitas. Tautan ini tidak menetapkan identitas, risiko, kecurigaan, pelanggaran, prioritas, penilaian, atau dasar penegakan.',
    back_inbox:'Kotak Masuk Intelijen',record_display_error:'Kesalahan tampilan catatan',record_display_error_help:'Catatan intelijen ini tidak dapat ditampilkan dengan aman. Catatan tetap tersimpan; kembali ke kotak masuk dan coba lagi setelah memuat ulang.',unexpected_display_error:'Kesalahan tampilan tak terduga',return_inbox:'Kembali ke Kotak Masuk Intelijen',refresh_record:'Muat ulang catatan',loading_record:'Memuat catatan intelijen...',access_denied:'Akses Ditolak',access_denied_help:'Anda tidak memiliki izin untuk mengakses catatan intelijen ini. Catatan mungkin berada di luar yurisdiksi Anda atau tidak tersedia pada tingkat akses saat ini.',intelligence_record:'Catatan intelijen',edit_record:'Edit catatan',
    correct_record:'Koreksi catatan · edit manusia',headline:'Judul',source_publisher:'Sumber / Penerbit',author:'Penulis',related_topics_label:'Topik Terkait',assigned_reviewer:'Peninjau yang Ditugaskan',original_preserved_help:'Teks sumber asli, bahasa, URL, dan berkas unggahan dipertahankan sebagaimana dikirim; lampirkan bukti tambahan alih-alih menggantinya.',english_translation:'Terjemahan Inggris',ai_unchanged_help:'Saran AI tetap tidak berubah. Catat koreksi manusia pada catatan analis.',analyst_notes:'Catatan Analis',save_corrections:'Simpan koreksi',
    original_source:'Sumber Asli',what_source_says:'ISI SUMBER',no_source_text:'Tidak ada teks sumber yang dimasukkan. Lihat URL asli atau materi terlampir.',view_full_source:'Lihat materi sumber lengkap · bukti dipertahankan',full_source_help:'Isi artikel di atas dapat dibersihkan untuk keterbacaan dan triage AI. Sumber lengkap dipertahankan di sini dan tidak pernah diganti secara diam-diam.',original_url:'URL Asli',open_original_source:'Buka sumber asli',author_account:'Penulis / Akun',platform_publisher:'Platform / Penerbit',published:'Diterbitkan',original_language:'Bahasa Asli',collected:'Dikumpulkan',translation:'Terjemahan',no_translation:'Belum ada terjemahan Inggris.',
    evidence_assessment:'Penilaian Bukti',evidence_type:'Jenis Bukti',verification_status:'Status Verifikasi',evidence_explain:'TERAMATI menjelaskan representasi sumber; BELUM DIVERIFIKASI berarti verifikasi sumber independen belum selesai. Validasi manusia tidak menetapkan pelanggaran.',mark_verified:'Tandai sumber DIVERIFIKASI MANUSIA',
    legacy_analysis:'Analisis Lama (jika tercatat)',ai_suggestion_not_finding:'SARAN AI · BUKAN TEMUAN',no_ai_analysis:'Belum ada analisis AI yang diterima.',review_ai_suggestions:'TINJAU SARAN AI',supporting_evidence:'Bukti Pendukung',no_files:'Tidak ada berkas terlampir.',attach_supporting_material:'Lampirkan materi pendukung asli (privat)',evidence_description:'Deskripsi bukti',upload_evidence:'Unggah bukti',
    related_intelligence:'Intelijen Terkait',entities:'Entitas',human_linked_watchlist:'Daftar Pantauan Tertaut oleh Manusia',watchlist_relationship_only:'Item Daftar Pantauan · Hanya hubungan entitas; tidak menyiratkan risiko, pelanggaran, atau prioritas.',view_watchlist_profile:'Lihat Profil Daftar Pantauan',human_review:'Tinjauan Manusia',decision:'Keputusan',timestamp:'Waktu',no_review_notes:'Belum ada catatan peninjauan.',validation_decision:'Keputusan Validasi',review_notes:'Catatan Peninjauan',geographic_pending_block:'Tinjauan ketidaksesuaian geografis masih menunggu. Validasi akhir diblokir sampai keputusan yurisdiksi diselesaikan.',triage_pending_block:'Selesaikan peninjauan semua saran Triage AI sebelum validasi akhir.',record_human_decision:'Catat keputusan manusia',restricted_reviewers:'Terbatas untuk peninjau berwenang.'
  }
};

const valueLabels={
  id:{
    'Critical':'Kritis','High':'Tinggi','Medium':'Sedang','Low':'Rendah',
    'Active':'Aktif','Inactive':'Tidak Aktif','Under Review':'Dalam Peninjauan',
    'Pending Review':'Menunggu Peninjauan','Awaiting Validation':'Menunggu Validasi',
    'Validated as Relevant Intelligence':'Divalidasi sebagai Intelijen Relevan',
    'Request More Information':'Minta Informasi Tambahan','Not Relevant':'Tidak Relevan',
    'Escalate for Further Review':'Eskalasi untuk Peninjauan Lanjutan',
    'UNVERIFIED':'BELUM DIVERIFIKASI','HUMAN_VERIFIED':'DIVERIFIKASI MANUSIA','VERIFIED':'DIVERIFIKASI',
    'OBSERVED':'TERAMATI','INFERRED':'INFERENSI',
    'NO SIGNAL IDENTIFIED':'TIDAK ADA SINYAL TERIDENTIFIKASI',
    'MONITOR':'PANTAU','REVIEW RECOMMENDED':'PENINJAUAN DIREKOMENDASIKAN',
    'POTENTIAL REGULATORY ISSUE':'POTENSI ISU REGULASI',
    'DISCOVERED':'DITEMUKAN','RELEVANT':'RELEVAN','NOT_RELEVANT':'TIDAK RELEVAN',
    'PROMOTED':'DITAMBAHKAN KE INTELIJEN'
  }
};

export function LanguageProvider({children}){
  const [language,setLanguageState]=useState(()=>localStorage.getItem('bawaslu-language')||'en');
  const setLanguage=next=>setLanguageState(next==='id'?'id':'en');
  useEffect(()=>{
    localStorage.setItem('bawaslu-language',language);
    document.documentElement.lang=language==='id'?'id':'en';
  },[language]);
  const api=useMemo(()=>({
    language,
    setLanguage,
    t:key=>translations[language]?.[key]??translations.en[key]??key,
    label:value=>valueLabels[language]?.[value]??value
  }),[language]);
  return <LanguageContext.Provider value={api}>{children}</LanguageContext.Provider>;
}

export function useLanguage(){
  const ctx=useContext(LanguageContext);
  if(!ctx)throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
