import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LanguageContext=createContext(null);

const translations={
  en:{
    workspace:'Workspace',future_modules:'Future modules',soon:'SOON',
    home:'Home',watchlist:'Watchlist',social_listening:'Social Listening',intelligence_inbox:'Intelligence Inbox',
    intelligence_assistant:'BAWASLU Intelligence Assistant',add_intelligence:'Add Intelligence',data_sources:'Data Sources',
    validation:'Validation',administration:'Administration',intelligence_command:'Intelligence Command',
    secure_workspace:'Secure workspace',authorized_user:'Authorized user',
    election_supervision_intelligence:'Election supervision / Intelligence',add:'Add',
    loading_access:'Loading BAWASLU access...',inactive_access:'Your BAWASLU access is inactive.',select:'Select',

    workspace_overview:'Workspace Overview',
    intelligence_situation:'Intelligence Situation',
    home_intro:'Operational overview of the existing BAWASLU workspace and the items that need attention now.',
    operational_metrics:'Operational metrics',
    authorized_scope_note:'Counts are limited to intelligence records available within your authorized scope.',
    open:'Open',
    pending_intelligence_review:'Pending Intelligence Review',
    pending_intelligence_detail:'Needs human review or validation.',
    validated_intelligence:'Validated Intelligence',
    validated_intelligence_detail:'Human-validated relevant intelligence.',
    unverified_evidence:'UNVERIFIED Evidence',
    unverified_evidence_detail:'Source verification is still pending.',
    jurisdiction_unresolved:'Jurisdiction Unresolved',
    jurisdiction_unresolved_detail:'Needs human jurisdiction confirmation.',
    ai_triage_awaiting_review:'AI Triage Awaiting Review',
    ai_triage_detail:'Generated suggestions still need analyst decisions.',
    social_review_queue:'Social Review Queue',
    social_review_detail:'Stored results awaiting human disposition.',
    attention_now:'What needs attention now',
    attention_rank_note:'Ranked by geographic mismatch, AI review, human review, jurisdiction and priority.',
    open_inbox:'Open inbox',
    geographic_mismatch:'Geographic mismatch',
    ai_triage_review:'AI triage review',
    pending_human_review:'Pending human review',
    critical_priority:'Critical priority',
    high_priority:'High priority',
    jurisdiction_not_confirmed:'Jurisdiction not confirmed',
    validated_monitoring:'Validated intelligence & monitoring queues',
    validated_monitoring_note:'Compact management view of validated intelligence, Watchlist state and stored Social Listening review work.',
    latest_validated:'Latest validated intelligence',
    view_all:'View all',
    watchlist_summary_unavailable:'Watchlist summary unavailable. The rest of Home remains available.',
    loading_watchlist_summary:'Loading Watchlist summary...',
    social_queue_unavailable:'Social Listening queue status is temporarily unavailable.',
    no_socialcrawl_search:'No SocialCrawl search was triggered.',
    loading_social_queue:'Loading stored Social Listening queue...',
    active:'Active',under_review:'Under Review',inactive:'Inactive',
    discovered:'Discovered',relevant:'Relevant',monitor:'Monitor',
    validated_label:'Validated',source_label:'Source',verification_label:'Verification',
    recent_activity:'Recent activity',
    recent_activity_note:'Latest recorded workspace actions. Activity failure does not block the operational dashboard.',
    recent_activity_unavailable:'Recent activity is temporarily unavailable.',
    no_recent_activity:'No recent activity yet.',
    system:'System',
    no_immediate_attention:'No intelligence currently requires immediate attention.',
    no_validated_scope:'No validated intelligence in your authorized scope yet.',
    untitled_intelligence:'Untitled intelligence',
    source_not_recorded:'Source not recorded',
    confirmed:'Confirmed',national:'National',

    collection_triage:'Collection / Triage',
    all_intelligence:'All intelligence',
    pending_review:'Pending Review',
    validated:'Validated',
    unverified:'UNVERIFIED',
    ai_triage_waiting:'AI Triage Awaiting Review',
    search_placeholder:'Search keywords, ID, entity or location...',
    all_prefix:'All',
    sort_recently_updated:'Recently updated',
    sort_newest_created:'Newest created',
    sort_oldest_created:'Oldest created',
    sort_highest_priority:'Highest priority',
    sort_intelligence_id:'Intelligence ID',
    view:'View',
    clear_all_filters:'Clear all filters',
    loading_intelligence:'Loading intelligence...',
    submitted_jurisdiction:'Submitted for national jurisdiction resolution. Regional users cannot access the record until it is confirmed.',
    match:'match',matches:'matches',
    records_authorized_scope:'records in authorized scope',
    record_authorized_scope:'record in authorized scope',
    filter_search:'Search',filter_date:'Date',filter_entity:'Entity',filter_verification:'Verification',
    filter_review_status:'Review status',filter_priority:'Priority',filter_province:'Province',
    filter_regency_city:'Regency / City',filter_platform:'Platform',filter_evidence_type:'Evidence type',
    filter_reviewer:'Reviewer',filter_source_type:'Source type',filter_supervision_signal:'Supervision signal',
    location:'Location',evidence:'Evidence',priority:'Priority',reviewer:'Reviewer',updated:'Updated',
    unassigned:'Unassigned',no_related_entity:'No related entity',
    source_type_not_recorded:'Source type not recorded',
    jurisdiction_unresolved_short:'Jurisdiction unresolved',
    geographic_review_required:'Geographic mismatch review required',
    no_match_current_filters:'No intelligence matches the current view and filters.',
    not_classified:'Not classified'
  },

  id:{
    workspace:'Ruang Kerja',future_modules:'Modul Mendatang',soon:'SEGERA',
    home:'Beranda',watchlist:'Daftar Pantauan',social_listening:'Pemantauan Media Sosial',intelligence_inbox:'Kotak Masuk Intelijen',
    intelligence_assistant:'Asisten Intelijen BAWASLU',add_intelligence:'Tambah Intelijen',data_sources:'Sumber Data',
    validation:'Validasi',administration:'Administrasi',intelligence_command:'Komando Intelijen',
    secure_workspace:'Ruang kerja aman',authorized_user:'Pengguna berwenang',
    election_supervision_intelligence:'Pengawasan Pemilu / Intelijen',add:'Tambah',
    loading_access:'Memuat akses BAWASLU...',inactive_access:'Akses BAWASLU Anda tidak aktif.',select:'Pilih',

    workspace_overview:'Ikhtisar Ruang Kerja',
    intelligence_situation:'Situasi Intelijen',
    home_intro:'Ikhtisar operasional ruang kerja BAWASLU dan hal-hal yang memerlukan perhatian saat ini.',
    operational_metrics:'Metrik Operasional',
    authorized_scope_note:'Jumlah dibatasi pada catatan intelijen yang tersedia dalam cakupan akses Anda.',
    open:'Buka',
    pending_intelligence_review:'Intelijen Menunggu Peninjauan',
    pending_intelligence_detail:'Memerlukan peninjauan atau validasi manusia.',
    validated_intelligence:'Intelijen Tervalidasi',
    validated_intelligence_detail:'Intelijen relevan yang telah divalidasi manusia.',
    unverified_evidence:'Bukti BELUM DIVERIFIKASI',
    unverified_evidence_detail:'Verifikasi sumber masih menunggu.',
    jurisdiction_unresolved:'Yurisdiksi Belum Ditentukan',
    jurisdiction_unresolved_detail:'Memerlukan konfirmasi yurisdiksi oleh manusia.',
    ai_triage_awaiting_review:'Triage AI Menunggu Peninjauan',
    ai_triage_detail:'Saran yang dihasilkan masih memerlukan keputusan analis.',
    social_review_queue:'Antrean Tinjauan Sosial',
    social_review_detail:'Hasil tersimpan menunggu keputusan manusia.',
    attention_now:'Yang Perlu Diperhatikan Sekarang',
    attention_rank_note:'Diurutkan berdasarkan ketidaksesuaian geografis, tinjauan AI, tinjauan manusia, yurisdiksi, dan prioritas.',
    open_inbox:'Buka Kotak Masuk',
    geographic_mismatch:'Ketidaksesuaian geografis',
    ai_triage_review:'Tinjauan triage AI',
    pending_human_review:'Menunggu tinjauan manusia',
    critical_priority:'Prioritas kritis',
    high_priority:'Prioritas tinggi',
    jurisdiction_not_confirmed:'Yurisdiksi belum dikonfirmasi',
    validated_monitoring:'Intelijen Tervalidasi & Antrean Pemantauan',
    validated_monitoring_note:'Tampilan ringkas untuk intelijen tervalidasi, status Daftar Pantauan, dan pekerjaan tinjauan Pemantauan Media Sosial yang tersimpan.',
    latest_validated:'Intelijen Tervalidasi Terbaru',
    view_all:'Lihat Semua',
    watchlist_summary_unavailable:'Ringkasan Daftar Pantauan sementara tidak tersedia. Bagian Beranda lainnya tetap tersedia.',
    loading_watchlist_summary:'Memuat ringkasan Daftar Pantauan...',
    social_queue_unavailable:'Status antrean Pemantauan Media Sosial sementara tidak tersedia.',
    no_socialcrawl_search:'Tidak ada pencarian SocialCrawl yang dijalankan.',
    loading_social_queue:'Memuat antrean Pemantauan Media Sosial yang tersimpan...',
    active:'Aktif',under_review:'Dalam Peninjauan',inactive:'Tidak Aktif',
    discovered:'Ditemukan',relevant:'Relevan',monitor:'Pantau',
    validated_label:'Divalidasi',source_label:'Sumber',verification_label:'Verifikasi',
    recent_activity:'Aktivitas Terbaru',
    recent_activity_note:'Tindakan terbaru yang tercatat di ruang kerja. Kegagalan aktivitas tidak memblokir dasbor operasional.',
    recent_activity_unavailable:'Aktivitas terbaru sementara tidak tersedia.',
    no_recent_activity:'Belum ada aktivitas terbaru.',
    system:'Sistem',
    no_immediate_attention:'Tidak ada intelijen yang saat ini memerlukan perhatian segera.',
    no_validated_scope:'Belum ada intelijen tervalidasi dalam cakupan akses Anda.',
    untitled_intelligence:'Intelijen Tanpa Judul',
    source_not_recorded:'Sumber belum tercatat',
    confirmed:'Dikonfirmasi',national:'Nasional',

    collection_triage:'Pengumpulan / Triage',
    all_intelligence:'Semua Intelijen',
    pending_review:'Menunggu Peninjauan',
    validated:'Tervalidasi',
    unverified:'BELUM DIVERIFIKASI',
    ai_triage_waiting:'Triage AI Menunggu Peninjauan',
    search_placeholder:'Cari kata kunci, ID, entitas, atau lokasi...',
    all_prefix:'Semua',
    sort_recently_updated:'Terakhir Diperbarui',
    sort_newest_created:'Terbaru Dibuat',
    sort_oldest_created:'Terlama Dibuat',
    sort_highest_priority:'Prioritas Tertinggi',
    sort_intelligence_id:'ID Intelijen',
    view:'Tampilan',
    clear_all_filters:'Hapus Semua Filter',
    loading_intelligence:'Memuat intelijen...',
    submitted_jurisdiction:'Diajukan untuk penyelesaian yurisdiksi nasional. Pengguna regional tidak dapat mengakses catatan hingga dikonfirmasi.',
    match:'cocok',matches:'cocok',
    records_authorized_scope:'catatan dalam cakupan akses',
    record_authorized_scope:'catatan dalam cakupan akses',
    filter_search:'Pencarian',filter_date:'Tanggal',filter_entity:'Entitas',filter_verification:'Verifikasi',
    filter_review_status:'Status Peninjauan',filter_priority:'Prioritas',filter_province:'Provinsi',
    filter_regency_city:'Kabupaten / Kota',filter_platform:'Platform',filter_evidence_type:'Jenis Bukti',
    filter_reviewer:'Peninjau',filter_source_type:'Jenis Sumber',filter_supervision_signal:'Sinyal Pengawasan',
    location:'Lokasi',evidence:'Bukti',priority:'Prioritas',reviewer:'Peninjau',updated:'Diperbarui',
    unassigned:'Belum Ditugaskan',no_related_entity:'Tidak ada entitas terkait',
    source_type_not_recorded:'Jenis sumber belum tercatat',
    jurisdiction_unresolved_short:'Yurisdiksi belum ditentukan',
    geographic_review_required:'Tinjauan ketidaksesuaian geografis diperlukan',
    no_match_current_filters:'Tidak ada intelijen yang cocok dengan tampilan dan filter saat ini.',
    not_classified:'Belum Diklasifikasikan'
  }
};

const valueLabels={
  id:{
    'Critical':'Kritis','High':'Tinggi','Medium':'Sedang','Low':'Rendah',
    'Active':'Aktif','Inactive':'Tidak Aktif','Under Review':'Dalam Peninjauan',
    'Pending Review':'Menunggu Peninjauan','Awaiting Validation':'Menunggu Validasi',
    'Validated as Relevant Intelligence':'Divalidasi sebagai Intelijen Relevan',
    'Request More Information':'Minta Informasi Tambahan','Not Relevant':'Tidak Relevan',
    'Escalate for Further Review':'Eskalasi untuk Peninjauan Lanjutan',
    'UNVERIFIED':'BELUM DIVERIFIKASI','HUMAN_VERIFIED':'DIVERIFIKASI MANUSIA','VERIFIED':'DIVERIFIKASI',
    'OBSERVED':'TERAMATI','INFERRED':'INFERENSI',
    'NO SIGNAL IDENTIFIED':'TIDAK ADA SINYAL TERIDENTIFIKASI',
    'MONITOR':'PANTAU','REVIEW RECOMMENDED':'PENINJAUAN DIREKOMENDASIKAN',
    'POTENTIAL REGULATORY ISSUE':'POTENSI ISU REGULASI',
    'DISCOVERED':'DITEMUKAN','RELEVANT':'RELEVAN','NOT_RELEVANT':'TIDAK RELEVAN',
    'PROMOTED':'DITAMBAHKAN KE INTELIJEN'
  }
};

export function LanguageProvider({children}){
  const [language,setLanguageState]=useState(()=>localStorage.getItem('bawaslu-language')||'en');
  const setLanguage=next=>setLanguageState(next==='id'?'id':'en');
  useEffect(()=>{
    localStorage.setItem('bawaslu-language',language);
    document.documentElement.lang=language==='id'?'id':'en';
  },[language]);
  const api=useMemo(()=>({
    language,
    setLanguage,
    t:key=>translations[language]?.[key]??translations.en[key]??key,
    label:value=>valueLabels[language]?.[value]??value
  }),[language]);
  return <LanguageContext.Provider value={api}>{children}</LanguageContext.Provider>;
}

export function useLanguage(){
  const ctx=useContext(LanguageContext);
  if(!ctx)throw new Error('useLanguage must be used inside LanguageProvider');
  return ctx;
}
